export const morningQuotes = [
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations V.20" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations X.16" },
  { text: "It is not death that a man should fear, but he should fear never beginning to live.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Receive without pride, relinquish without struggle.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Do not indulge in dreams of what you have not, but count the blessings you actually possess.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "If it is not right, do not do it; if it is not true, do not say it.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The best revenge is not to be like your enemy.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations VI.6" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Never esteem anything as of advantage to you that will make you break your word or lose your self-respect.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Do not act as if you had ten thousand years to live.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Loss is nothing else but change, and change is nature\'s delight.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations IX.35" },
  { text: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations V.16" },
  { text: "Perfection of character is this: to live each day as if it were your last.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations VII.69" },
  { text: "Very little is needed to make a happy life; it is all within yourself in your way of thinking.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "How much more grievous are the consequences of anger than the causes of it.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "In your actions, don\'t procrastinate. In your conversations, don\'t confuse. In your thoughts, don\'t wander.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Reject your sense of injury and the injury itself disappears.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The art of living is more like wrestling than dancing.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations VII.61" },
  { text: "To live happily is an inward power of the soul.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "He who lives in harmony with himself lives in harmony with the universe.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Adapt yourself to the things among which your lot has been cast, and love sincerely the fellow creatures with whom destiny has ordained that you shall live.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Everything harmonizes with me that is harmonious to thee, O Universe.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations IV.23" },
  { text: "If someone is able to show me that what I think or do is not right, I will happily change.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations VII.49" },
  { text: "Nowhere can you find a more peaceful or untroubled retreat than in your own soul. Give yourself this retreat, and renew yourself.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations IV.3" },
  { text: "Because your own strength is unequal to the task, do not assume that it is beyond the powers of man.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Forward, as occasion offers. Never look round to see whether any shall note it... Be satisfied with success in even the smallest matter.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "How much time he gains who does not look to see what his neighbor says or does or thinks.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Ask yourself at every moment, \'Is this necessary?\'", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The universe is transformation; life is opinion.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca", source: "Letters", ref: "Letters 101.10" },
  { text: "There are more things likely to frighten us than there are to crush us; we suffer more often in imagination than in reality.", author: "Seneca", source: "Letters", ref: "Letters 13.4" },
  { text: "True happiness is to enjoy the present, without anxious dependence upon the future.", author: "Seneca", source: "Letters" },
  { text: "He suffers more than necessary, who suffers before it is necessary.", author: "Seneca", source: "Letters", ref: "Letters 98.8" },
  { text: "It\'s not because things are difficult that we dare not venture. It\'s because we dare not venture that they are difficult.", author: "Seneca", source: "Letters", ref: "Letters 104.26" },
  { text: "One who is everywhere is nowhere.", author: "Seneca", source: "Letters" },
  { text: "Philosophy promises above all: common sense, humanity, and fellowship.", author: "Seneca", source: "Letters" },
  { text: "The company of many is harmful.", author: "Seneca", source: "Letters" },
  { text: "Turn to these studies.", author: "Seneca", source: "Letters" },
  { text: "The time will come when diligent research over long periods will bring to light things which now lie hidden.", author: "Seneca", source: "Letters" },
  { text: "No man was ever wise by chance.", author: "Seneca", source: "Letters" },
  { text: "A sword never kills anybody; it is a tool in the killer\'s hand.", author: "Seneca", source: "Letters" },
  { text: "I am not born for one corner; the whole world is my native land.", author: "Seneca", source: "Letters", ref: "Letters 28.4" },
  { text: "Let us prepare our minds as if we had come to the very end of life.", author: "Seneca", source: "Letters" },
  { text: "While we delay, life passes.", author: "Seneca", source: "Letters", ref: "Letters 1.3" },
  { text: "If you wish to be loved, love.", author: "Seneca", source: "Letters", ref: "Letters 9.6" },
  { text: "The good man differs from other men not in time but in quality of life.", author: "Seneca", source: "Letters" },
  { text: "We must not hate our enemies merely because they are difficult.", author: "Seneca", source: "Letters" },
  { text: "There is no great genius without a touch of madness.", author: "Seneca", source: "On Tranquility of Mind" },
  { text: "There is no easy way from the earth to the stars.", author: "Seneca", source: "Hercules Furens", ref: "Hercules Furens 437" },
  { text: "Other men\'s goods please us, ours please other men.", author: "Seneca", source: "On Tranquility of Mind" },
  { text: "No man leaves life any differently than he entered it.", author: "Seneca", source: "Letters" },
  { text: "Retreat into yourself as much as you can.", author: "Seneca", source: "Letters", ref: "Letters 7.8" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus", source: "Enchiridion", ref: "Enchiridion 1" },
  { text: "First say to yourself what you would be; then do what you have to do.", author: "Epictetus", source: "Discourses" },
  { text: "How long are you going to wait before you demand the best for yourself?", author: "Epictetus", source: "Discourses" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus", source: "Discourses" },
  { text: "You become what you give your attention to.", author: "Epictetus", source: "Discourses" },
  { text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus", source: "Enchiridion", ref: "Enchiridion 13" },
  { text: "Seek not the good in external things; seek it in yourself.", author: "Epictetus", source: "Discourses" },
  { text: "The essence of philosophy is that a man should so live that his happiness shall depend as little as possible on external things.", author: "Epictetus", source: "Discourses" },
  { text: "First learn the meaning of what you say, and then speak.", author: "Epictetus", source: "Discourses" },
  { text: "No man who is not at times a fool can be a wise man.", author: "Epictetus", source: "Fragments" },
  { text: "Nothing is more ignoble than pride.", author: "Epictetus", source: "Discourses" },
  { text: "Practice yourself, for heaven\'s sake, in little things; and thence proceed to greater.", author: "Epictetus", source: "Discourses" },
  { text: "Know, first, who you are, and then adorn yourself accordingly.", author: "Epictetus", source: "Discourses" },
  { text: "If you ever find yourself in the position of a man who has nothing, consider yourself rich.", author: "Epictetus", source: "Discourses" },
  { text: "He is a free man who fears nothing.", author: "Epictetus", source: "Discourses" },
  { text: "Reason is not measured by size or height, but by principle.", author: "Epictetus", source: "Discourses" },
  { text: "We should not moor a ship with one anchor, or our life with one hope.", author: "Epictetus", source: "Discourses" },
  { text: "Only the educated are free.", author: "Epictetus", source: "Discourses" },
  { text: "Wealth is the slave of a wise man. The master of a fool.", author: "Seneca", source: "Letters" },
  { text: "No great thing is created suddenly.", author: "Epictetus", source: "Discourses" },
  { text: "Be careful to leave your sons well instructed rather than rich, for the hopes of the instructed are better than the wealth of the ignorant.", author: "Epictetus", source: "Fragments" },
  { text: "It is the part of an uneducated person to blame others where he himself fares ill; to blame oneself is the part of one whose education has begun.", author: "Epictetus", source: "Enchiridion", ref: "Enchiridion 5" },
  { text: "The beginning of philosophy is to know the condition of one\'s own mind.", author: "Epictetus", source: "Discourses" },
  { text: "Try to get what is your own. Don\'t cry for what is not.", author: "Epictetus", source: "Discourses" },
  { text: "He is a wise man who does not grieve for things he has not, but rejoices for those which he has.", author: "Epictetus", source: "Fragments" },
  { text: "If you wish to be beautiful, practice beautiful deeds.", author: "Epictetus", source: "Discourses" },
  { text: "Think how many years have passed.", author: "Seneca", source: "Letters" },
  { text: "You will find life short if you crowd everything into it.", author: "Seneca", source: "Letters" },
  { text: "You should bear others\' ways as you bear your own.", author: "Seneca", source: "Letters" },
  { text: "The willing are led by fate; the unwilling are dragged.", author: "Seneca", source: "Letters", ref: "Letters 107.11" },
  { text: "We are all driven to the same place.", author: "Seneca", source: "Letters" },
  { text: "Ask nothing of the gods but what they are able to give.", author: "Seneca", source: "Letters" },
  { text: "Where the disease is greatest, the physician is needed most.", author: "Seneca", source: "Letters" },
  { text: "He who has injured you was either stronger or weaker than you.", author: "Seneca", source: "On Benefits" },
  { text: "You act like mortals in all that you fear, and like immortals in all that you desire.", author: "Seneca", source: "On the Shortness of Life", ref: "On the Shortness of Life 3.4" },
  { text: "The courage which looks danger in the face is far preferable to the courage which flies from it.", author: "Seneca", source: "Letters" },
  { text: "Every hour comes to you precious and unique.", author: "Seneca", source: "Letters" },
  { text: "No man is eloquent in his own cause.", author: "Seneca", source: "Letters" },
  { text: "He who is going to do an injury is already doing it.", author: "Seneca", source: "Letters" },
  { text: "If you do not know to which harbor you are steering, no wind is favorable.", author: "Seneca", source: "Letters", ref: "Letters 71.3" },
  { text: "Leisure without literature is death and burial of a living man.", author: "Seneca", source: "Letters" },
  { text: "Divide your time and cultivate it; otherwise nothing important gets done.", author: "Seneca", source: "Letters" },
  { text: "It does not matter how many books you have, but how good they are.", author: "Seneca", source: "Letters" },
  { text: "Philosophy is difficult in practice, but believe me, this is its very help.", author: "Seneca", source: "Letters" },
  { text: "No one can wear a mask for long.", author: "Seneca", source: "Letters" },
  { text: "None is good except the simple.", author: "Seneca", source: "Letters" },
  { text: "The true lover of philosophy should be more devoted to a good mind than to anything else.", author: "Seneca", source: "Letters" },
  { text: "Not to advance is to go back.", author: "Seneca", source: "Letters" },
  { text: "Everything is alien to us; time alone is ours.", author: "Seneca", source: "Letters", ref: "Letters 1.3" },
  { text: "Do everything as if some good man were watching.", author: "Seneca", source: "Letters" },
  { text: "What is not good for the swarm is not good for the bee.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations VI.54" },
  { text: "Think not of what is lacking; think of what you have.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Your mind will take the shape of what you frequently hold in thought.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Wherever a man can live, there he can also live well.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Whatever the present moment contains, accept it as if you had chosen it.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Give yourself a gift: the present moment.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations VIII.44" },
  { text: "Execute every act of thy life as though it were thy last.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations II.5" },
  { text: "Be tolerant with others and strict with yourself.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Nothing happens to any man that he is not formed by nature to bear.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations V.18" },
  { text: "Dig within. Within is the wellspring of good; ever dig, and it will ever flow.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations VII.59" },
  { text: "The first step: Don\'t be anxious. Nature controls it all.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Be content to seem what you really are.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Do not seek to have events happen as you want them to, but wish them to happen as they do, and your life will go well.", author: "Epictetus", source: "Enchiridion", ref: "Enchiridion 8" },
  { text: "There is only one way to happiness, and that is to cease worrying about things which are beyond the power of our will.", author: "Epictetus", source: "Discourses" },
  { text: "If you want to be a writer, write. If you want to be a reader, read.", author: "Epictetus", source: "Discourses" },
  { text: "Freedom is not achieved by satisfying desire, but by eliminating it.", author: "Epictetus", source: "Discourses" },
  { text: "It is impossible for a man to learn what he thinks he already knows.", author: "Epictetus", source: "Discourses" },
  { text: "If you would cure anger, do not feed it. Say to yourself: \'I used to be angry every day; then every other day; then once in three days.\'", author: "Epictetus", source: "Enchiridion" },
  { text: "The two powers which in my opinion constitute a wise man are those of bearing and forbearing.", author: "Epictetus", source: "Fragments" },
  { text: "All philosophy lies in two words: sustain and abstain.", author: "Epictetus", source: "Fragments" },
  { text: "Every habit and faculty is preserved and increased by correspondent actions.", author: "Epictetus", source: "Discourses" },
  { text: "The loftier the building, the deeper the foundation.", author: "Epictetus", source: "Discourses" },
  { text: "Nothing outside of the will can hinder or harm the will; it can only harm itself.", author: "Epictetus", source: "Discourses" },
  { text: "You can bind up my leg, but not even Zeus has the power to break my freedom of choice.", author: "Epictetus", source: "Discourses" },
  { text: "The goal of life is living in agreement with nature.", author: "Zeno of Citium", source: "Diogenes Laertius", ref: "Diogenes Laertius VII.87" },
  { text: "Happiness is a good flow of life.", author: "Zeno of Citium", source: "Diogenes Laertius", ref: "Diogenes Laertius VII.88" },
  { text: "We have two ears and one mouth, so we should listen more than we say.", author: "Zeno of Citium", source: "Diogenes Laertius", ref: "Diogenes Laertius VII.23" },
  { text: "Better to trip with the feet than with the tongue.", author: "Zeno of Citium", source: "Diogenes Laertius", ref: "Diogenes Laertius VII.26" },
  { text: "All things are parts of one single system, which is called nature.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Do not indulge hope to the point of forgetting the present.", author: "Musonius Rufus", source: "Lectures" },
  { text: "The philosopher must heal himself before he attempts to heal others.", author: "Musonius Rufus", source: "Lectures" },
  { text: "It is not possible to live well today unless you treat it as your last day.", author: "Musonius Rufus", source: "Lectures" },
  { text: "Choose always the life that is most useful, and habit will render it the most agreeable.", author: "Musonius Rufus", source: "Lectures" },
  { text: "Those who have wisdom and love are the only ones who are rich.", author: "Musonius Rufus", source: "Lectures" },
  { text: "The person who seeks beauty will not find it; the person who seeks virtue will find beauty too.", author: "Musonius Rufus", source: "Lectures" },
  { text: "We suffer the punishment of those who wish to be gods; we are not content to live simply and justly.", author: "Musonius Rufus", source: "Lectures" },
  { text: "You should not be disturbed about having to deal with difficult people.", author: "Musonius Rufus", source: "Lectures" },
  { text: "To have good judgment, one must first have knowledge.", author: "Musonius Rufus", source: "Lectures" },
  { text: "I begin to speak only when I\'m certain what I\'ll say isn\'t better left unsaid.", author: "Cato", source: "Plutarch" },
  { text: "How long have you been putting off living?", author: "Seneca", source: "On the Shortness of Life", ref: "On the Shortness of Life 3.5" },
  { text: "While we teach, we learn.", author: "Seneca", source: "Letters" },
  { text: "The mind that is anxious about the future is miserable.", author: "Seneca", source: "Letters" },
  { text: "You want to know what I\'ve been doing? I\'ve been keeping myself employed.", author: "Seneca", source: "Letters" },
  { text: "It is a rough road that leads to the heights of greatness.", author: "Seneca", source: "Letters" },
  { text: "Collect and save the time which has hitherto been cut into and stolen from you.", author: "Seneca", source: "Letters", ref: "Letters 1.1" },
  { text: "Observe always that everything is the result of change.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Whatever befalls thee was preordained for thee from eternity.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "How ridiculous and how strange to be surprised at anything which happens in life.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Understand at last that you have something in you more powerful and divine than what causes the bodily passions.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The greatest obstacle to living is expectancy.", author: "Seneca", source: "On the Shortness of Life", ref: "On the Shortness of Life 9.1" },
  { text: "What need is there to weep over parts of life? The whole of it calls for tears.", author: "Seneca", source: "On the Shortness of Life" },
  { text: "One of the most beautiful qualities of true friendship is to understand and to be understood.", author: "Seneca", source: "Letters" },
  { text: "It is not the man who has little, but the man who craves more, that is poor.", author: "Seneca", source: "Letters" },
  { text: "To wish to be well is a part of becoming well.", author: "Seneca", source: "Letters" },
  { text: "He who spends time regretting the past loses the present and risks the future.", author: "Seneca", source: "Letters" },
  { text: "Nothing is burdensome if taken lightly.", author: "Seneca", source: "Letters" },
  { text: "Begin. To begin is half the work. Let half still remain. Again begin this, and thou wilt have finished.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "If you realize that all things change, there is nothing you will try to hold on to.", author: "Epictetus", source: "Discourses" },
  { text: "Act well your given part.", author: "Epictetus", source: "Enchiridion", ref: "Enchiridion 17" },
  { text: "A man\'s life is but a moment; his existence a flux.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The memory of everything is very soon overwhelmed in time.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "How much better to persist in poverty than to make an unworthy profit.", author: "Seneca", source: "Letters" },
  { text: "Do not be ashamed of needing help. You have a duty to fulfill just like a soldier on the wall of battle.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations VII.7" },
  { text: "If what you hold to be best is to be found in yourself — in your thoughts — why are you troubled?", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Everything — a horse, a vine — is created for some duty. For what task, then, were you yourself created?", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations VIII.19" },
  { text: "Conduct your life according to truth.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Apply yourself not to passivity, but to excellence.", author: "Epictetus", source: "Discourses" },
  { text: "Philosophy is first concerned with keeping the ruling faculty without violence.", author: "Epictetus", source: "Discourses" },
  { text: "The difficulty of this practice is not in the knowing but in the doing.", author: "Epictetus", source: "Discourses" },
  { text: "Consider how much more often you suffer from your anger and grief than from those very things for which you are angry and grieved.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations XI.18" },
  { text: "Time is a river, a violent current of events, glimpsed once and already carried past us.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations IV.43" },
  { text: "Keep in mind that it is not he who gives abuse or blows who affronts, but the view we take of these things as insulting.", author: "Epictetus", source: "Enchiridion", ref: "Enchiridion 20" },
  { text: "If you would not have a man flinch when the crisis comes, train him before it comes.", author: "Seneca", source: "Letters" },
  { text: "To learn how to die is to unlearn how to be a slave.", author: "Seneca", source: "Letters", ref: "Letters 26.10" },
  { text: "The unexamined life is not worth living.", author: "Socrates", source: "Apology", ref: "Apology 38a" },
  { text: "I know that I know nothing.", author: "Socrates", source: "Apology" },
  { text: "Wonder is the beginning of wisdom.", author: "Socrates", source: "Theaetetus" },
  { text: "He who is unable to live in society, or who has no need because he is sufficient for himself, must be either a beast or a god.", author: "Aristotle", source: "Politics", ref: "Politics I.2" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", source: "Diogenes Laertius", ref: "Diogenes Laertius V.18" },
  { text: "The least initial deviation from the truth is multiplied later a thousandfold.", author: "Aristotle", source: "On the Heavens" },
  { text: "Poverty is the parent of revolution and crime.", author: "Aristotle", source: "Politics", ref: "Politics II.6" },
  { text: "What is a friend? A single soul dwelling in two bodies.", author: "Aristotle", source: "Diogenes Laertius", ref: "Diogenes Laertius V.20" },
  { text: "Without friends no one would choose to live, though he had all other goods.", author: "Aristotle", source: "Nicomachean Ethics", ref: "Nicomachean Ethics VIII.1" },
  { text: "The high-minded man must care more for truth than for what people think.", author: "Aristotle", source: "Nicomachean Ethics", ref: "Nicomachean Ethics IV.3" },
  { text: "Those who educate children well are more to be honored than they who produce them.", author: "Aristotle", source: "Diogenes Laertius", ref: "Diogenes Laertius V.19" },
  { text: "When you wake, expect to meet people who are difficult: meddling, arrogant, ungrateful. They are this way because they cannot tell good from evil. But they share your nature, and no one can truly harm you. You were made to work with them, not against them.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations II.1" },
  { text: "Give me the Serenity to accept the things I cannot change,\nThe Courage to change the things I can,\nAnd the Wisdom to know the difference.", author: "Reinhold Niebuhr", source: "The Serenity Prayer" },
  { text: "Some things are within our control and some are not. Within our control are opinion, desire, aversion, and, in a word, whatever is our own doing. Not within our control are the body, property, and reputation, whatever is not our own doing.", author: "Epictetus", source: "Enchiridion", ref: "Enchiridion 1" },
  { text: "At dawn, when you have trouble getting out of bed, tell yourself: I have to go to work, as a human being. What do I have to complain of, if I'm going to do what I was born for, the things I was brought into the world to do?", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations V.1" },
  { text: "Lay down for yourself, at the outset, a certain stamp and type of character, which you are to maintain whether you are by yourself or meeting with people.", author: "Epictetus", source: "Enchiridion", ref: "Enchiridion 33" },
  { text: "The mark of a moderate man is freedom from his own ideas.", author: "Lao Tzu", source: "Tao Te Ching" },
  { text: "Fortune favors the bold.", author: "Virgil", source: "Aeneid" },
  { text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Ian Maclaren", source: "attributed" },
  { text: "One must cultivate one's garden.", author: "Voltaire", source: "Candide" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant", source: "The Story of Philosophy" },
  { text: "Courage is the first of human qualities because it is the quality which guarantees the others.", author: "Winston Churchill", source: "attributed" },
  { text: "A person's character is their destiny.", author: "Heraclitus", source: "Fragments" },
  { text: "Grasp the subject, the words will follow.", author: "Cato the Elder", source: "attributed" },
  { text: "Know thyself.", author: "Delphic maxim", source: "Temple of Apollo" },
  { text: "He who is not contented with what he has would not be contented with what he would like to have.", author: "Epicurus", source: "Vatican Sayings" },
  { text: "Do not do to others what angers you if done to you by others.", author: "Isocrates", source: "To Nicocles" },
  { text: "Pardon one offense and you encourage the commission of many.", author: "Publilius Syrus", source: "Sentences" },
];

export const mementoMoriQuotes = [
  { text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations II.11" },
  { text: "Think of yourself as dead. You have lived your life. Now take what's left and live it properly.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations VII.56" },
  { text: "Let us postpone nothing. Let us balance life's books each day.", author: "Seneca", source: "Letters" },
  { text: "The person who fears death will never do anything worth doing.", author: "Seneca", source: "Letters" },
  { text: "How many have laid waste to your life when you were unaware of what you were losing?", author: "Seneca", source: "On the Shortness of Life", ref: "On the Shortness of Life 3.3" },
  { text: "It is not that we have a short time to live, but that we waste much of it. Life is long enough if you know how to use it.", author: "Seneca", source: "On the Shortness of Life", ref: "On the Shortness of Life 1.3" },
  { text: "Death is not an evil. What is it then? The one law mankind has that is free of all discrimination.", author: "Seneca", source: "Letters" },
  { text: "Perfecting yourself is the foundation of perfecting everything else.", author: "Epictetus", source: "Discourses" },
  { text: "Ask yourself at day's end: What did I do well? What did I do badly? What did I leave undone? Walk through each in turn.", author: "Epictetus", source: "Discourses" },
  { text: "Let us go to our sleep with joy and gladness; let us say, I have lived, and have run the course that Fortune set for me.", author: "Seneca", source: "Letters", ref: "Letters 12.9" },
  { text: "Reflect often upon the rapidity with which all existing things pass away and are carried out of sight.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations V.23" },
  { text: "Hold every hour in your grasp. Lay hold of today, and you will depend less upon tomorrow.", author: "Seneca", source: "Letters", ref: "Letters 1.2" },
  { text: "Today I escaped anxiety. Or no, I discarded it, because it was within me.", author: "Marcus Aurelius", source: "Meditations", ref: "Meditations IX.13" },
];

export function getDailyQuote(pool, offset = 0) {
  const today = new Date();
  const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 86400000);
  return pool[(dayOfYear + offset) % pool.length];
}