export const morningQuotes = [
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "It is not death that a man should fear, but he should fear never beginning to live.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Receive without pride, relinquish without struggle.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Do not indulge in dreams of what you have not, but count the blessings you actually possess.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "If it is not right, do not do it; if it is not true, do not say it.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The best revenge is not to be like your enemy.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Never esteem anything as of advantage to you that will make you break your word or lose your self-respect.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Do not act as if you had ten thousand years to live.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Loss is nothing else but change, and change is nature\'s delight.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Think of yourself as dead. You have lived your life. Now take what\'s left and live it properly.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Perfection of character is this: to live each day as if it were your last.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Very little is needed to make a happy life; it is all within yourself in your way of thinking.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "What we do now echoes in eternity.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "How much more grievous are the consequences of anger than the causes of it.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "In your actions, don\'t procrastinate. In your conversations, don\'t confuse. In your thoughts, don\'t wander.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Reject your sense of injury and the injury itself disappears.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The art of living is more like wrestling than dancing.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "To live happily is an inward power of the soul.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "He who lives in harmony with himself lives in harmony with the universe.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Adapt yourself to the things among which your lot has been cast, and love sincerely the fellow creatures with whom destiny has ordained that you shall live.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "When you wake up in the morning, tell yourself: the people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous and surly.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Everything harmonizes with me that is harmonious to thee, O Universe.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Our life is what our thoughts make it.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "If someone is able to show me that what I think or do is not right, I will happily change.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Begin the morning by saying to thyself, I shall meet with the busy-body, the ungrateful, arrogant, deceitful, envious, unsocial.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Nowhere can man find a quieter or more untroubled retreat than in his own soul.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Because your own strength is unequal to the task, do not assume that it is beyond the powers of man.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The object in life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Forward, as occasion offers. Never look round to see whether any shall note it... Be satisfied with success in even the smallest matter.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "If it is not right do it not; if it is not true speak it not.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "How much time he gains who does not look to see what his neighbor says or does or thinks.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Ask yourself at every moment, \'Is this necessary?\'", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The universe is transformation; life is opinion.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "He who fears death will never do anything worthy of a living man.", author: "Seneca", source: "Letters" },
  { text: "The whole future lies in uncertainty: live immediately.", author: "Seneca", source: "Letters" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca", source: "Letters" },
  { text: "We suffer more in imagination than in reality.", author: "Seneca", source: "Letters" },
  { text: "True happiness is to enjoy the present, without anxious dependence upon the future.", author: "Seneca", source: "Letters" },
  { text: "It is not the man who has too little, but the man who craves more, that is poor.", author: "Seneca", source: "Letters" },
  { text: "He suffers more than necessary, who suffers before it is necessary.", author: "Seneca", source: "Letters" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca", source: "Letters" },
  { text: "Retire into yourself as much as possible.", author: "Seneca", source: "Letters" },
  { text: "It\'s not because things are difficult that we dare not venture. It\'s because we dare not venture that they are difficult.", author: "Seneca", source: "Letters" },
  { text: "No man is free who is not master of himself.", author: "Seneca", source: "Letters" },
  { text: "Omnia aliena sunt, tempus tantum nostrum est. All things are alien; time alone is ours.", author: "Seneca", source: "Letters" },
  { text: "Dum differtur vita transcurrit. While we are postponing, life speeds by.", author: "Seneca", source: "Letters" },
  { text: "Recede in te ipse. Withdraw into yourself.", author: "Seneca", source: "Letters" },
  { text: "Nusquam est qui ubique est. One who is everywhere is nowhere.", author: "Seneca", source: "Letters" },
  { text: "Hoc primum philosophia promittit: sensum communem, humanitatem et congregationem. Philosophy promises above all: common sense, humanity, and fellowship.", author: "Seneca", source: "Letters" },
  { text: "Per aspera ad astra. Through hardship to the stars.", author: "Seneca", source: "Letters" },
  { text: "Inimica est multorum conversatio. The company of many is harmful.", author: "Seneca", source: "Letters" },
  { text: "Confer te ad haec studia. Turn to these studies.", author: "Seneca", source: "Letters" },
  { text: "The time will come when diligent research over long periods will bring to light things which now lie hidden.", author: "Seneca", source: "Letters" },
  { text: "No man was ever wise by chance.", author: "Seneca", source: "Letters" },
  { text: "Every new beginning comes from some other beginning\'s end.", author: "Seneca", source: "Letters" },
  { text: "A sword never kills anybody; it is a tool in the killer\'s hand.", author: "Seneca", source: "Letters" },
  { text: "I am not born for one corner; the whole world is my native land.", author: "Seneca", source: "Letters" },
  { text: "Audentes Fortuna iuvat. Fortune favors the bold.", author: "Seneca", source: "Letters" },
  { text: "Let us prepare our minds as if we had come to the very end of life.", author: "Seneca", source: "Letters" },
  { text: "Dum differtur vita transcurrit. While we delay, life passes.", author: "Seneca", source: "Letters" },
  { text: "If you wish to be loved, love.", author: "Seneca", source: "Letters" },
  { text: "The good man differs from other men not in time but in quality of life.", author: "Seneca", source: "Letters" },
  { text: "Quia difficiles habemus inimicos non debemus eos immerito tantum odisse. We must not hate our enemies merely because they are difficult.", author: "Seneca", source: "Letters" },
  { text: "There is no great genius without a touch of madness.", author: "Seneca", source: "Letters" },
  { text: "We are more often frightened than hurt, and we suffer more from imagination than from reality.", author: "Seneca", source: "Letters" },
  { text: "Omnia, Lucili, aliena sunt, tempus tantum nostrum est.", author: "Seneca", source: "Letters" },
  { text: "Recede in te ipse quantum potes.", author: "Seneca", source: "Letters" },
  { text: "Nisi sapientiae deditus eris, non poteris esse felix.", author: "Seneca", source: "Letters" },
  { text: "Hoc primum philosophia promittit, sensum communem, humanitatem et congregationem.", author: "Seneca", source: "Letters" },
  { text: "Nusquam est qui ubique est.", author: "Seneca", source: "On Tranquility of Mind" },
  { text: "Dum differtur vita transcurrit.", author: "Seneca", source: "On the Shortness of Life" },
  { text: "Omnes, Lucili, aliena vivimus.", author: "Seneca", source: "On the Shortness of Life" },
  { text: "Non est ad astra mollis e terris via. There is no easy way from the earth to the stars.", author: "Seneca", source: "Hercules Furens" },
  { text: "Aliena nobis, nostra plus aliis placent. Other men\'s goods please us, ours please other men.", author: "Seneca", source: "On Tranquility of Mind" },
  { text: "Nemo non ita exit e vita, tamquam modo intraverit. No man leaves life any differently than he entered it.", author: "Seneca", source: "Letters" },
  { text: "Plura sunt quae nos terrent quam quae premunt. More things frighten us than crush us.", author: "Seneca", source: "Letters" },
  { text: "Recede in te ipse quantum potes. Retreat into yourself as much as you can.", author: "Seneca", source: "Letters" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus", source: "Enchiridion" },
  { text: "First say to yourself what you would be; then do what you have to do.", author: "Epictetus", source: "Discourses" },
  { text: "How long are you going to wait before you demand the best for yourself?", author: "Epictetus", source: "Discourses" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus", source: "Discourses" },
  { text: "Seek not that the things which happen should happen as you wish; but wish the things which happen to be as they are.", author: "Epictetus", source: "Enchiridion" },
  { text: "Man is disturbed not by things, but by the opinions about things.", author: "Epictetus", source: "Enchiridion" },
  { text: "You become what you give your attention to.", author: "Epictetus", source: "Discourses" },
  { text: "It\'s not what happens to you, but how you react to it that matters.", author: "Epictetus", source: "Enchiridion" },
  { text: "The key is to keep company only with people who uplift you.", author: "Epictetus", source: "Discourses" },
  { text: "Freedom is the only worthy goal in life.", author: "Epictetus", source: "Discourses" },
  { text: "Don\'t explain your philosophy. Embody it.", author: "Epictetus", source: "Discourses" },
  { text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus", source: "Enchiridion" },
  { text: "Men are disturbed not by the things which happen, but by the opinions about the things.", author: "Epictetus", source: "Enchiridion" },
  { text: "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", author: "Epictetus", source: "Fragments" },
  { text: "The greater the difficulty, the more the glory in surmounting it.", author: "Epictetus", source: "Discourses" },
  { text: "Seek not the good in external things; seek it in yourself.", author: "Epictetus", source: "Discourses" },
  { text: "Circumstances don\'t make the man, they only reveal him to himself.", author: "Epictetus", source: "Discourses" },
  { text: "He who laughs at himself never runs out of things to laugh at.", author: "Epictetus", source: "Fragments" },
  { text: "The essence of philosophy is that a man should so live that his happiness shall depend as little as possible on external things.", author: "Epictetus", source: "Discourses" },
  { text: "We cannot choose our external circumstances, but we can always choose how we respond to them.", author: "Epictetus", source: "Enchiridion" },
  { text: "First learn the meaning of what you say, and then speak.", author: "Epictetus", source: "Discourses" },
  { text: "No man who is not at times a fool can be a wise man.", author: "Epictetus", source: "Fragments" },
  { text: "Nothing is more ignoble than pride.", author: "Epictetus", source: "Discourses" },
  { text: "All philosophy lies in two words, sustain and abstain.", author: "Epictetus", source: "Fragments" },
  { text: "Practice yourself, for heaven\'s sake, in little things; and thence proceed to greater.", author: "Epictetus", source: "Discourses" },
  { text: "Know, first, who you are, and then adorn yourself accordingly.", author: "Epictetus", source: "Discourses" },
  { text: "If you ever find yourself in the position of a man who has nothing, consider yourself rich.", author: "Epictetus", source: "Discourses" },
  { text: "Attach yourself to what is spiritually superior, regardless of what other people think or do.", author: "Epictetus", source: "Enchiridion" },
  { text: "The loftier the building, the deeper must the foundation be laid.", author: "Epictetus", source: "Discourses" },
  { text: "He is a free man who fears nothing.", author: "Epictetus", source: "Discourses" },
  { text: "Reason is not measured by size or height, but by principle.", author: "Epictetus", source: "Discourses" },
  { text: "We should not moor a ship with one anchor, or our life with one hope.", author: "Epictetus", source: "Discourses" },
  { text: "If you want to be a writer, write.", author: "Epictetus", source: "Discourses" },
  { text: "What you think of yourself is much more important than what others think of you.", author: "Epictetus", source: "Enchiridion" },
  { text: "Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.", author: "Epictetus", source: "Discourses" },
  { text: "Only the educated are free.", author: "Epictetus", source: "Discourses" },
  { text: "Wealth is the slave of a wise man. The master of a fool.", author: "Seneca", source: "Letters" },
  { text: "Seek freedom and it will elude you. Seek justice and you will find them both.", author: "Epictetus", source: "Discourses" },
  { text: "No great thing is created suddenly.", author: "Epictetus", source: "Discourses" },
  { text: "Be careful to leave your sons well instructed rather than rich, for the hopes of the instructed are better than the wealth of the ignorant.", author: "Epictetus", source: "Fragments" },
  { text: "It is the part of an uneducated person to blame others where he himself fares ill; to blame oneself is the part of one whose education has begun.", author: "Epictetus", source: "Enchiridion" },
  { text: "It takes more than just a good looking body. You\'ve got to have the heart and soul to go with it.", author: "Epictetus", source: "Discourses" },
  { text: "Make the best of what is in our power, and take the rest as it occurs.", author: "Epictetus", source: "Discourses" },
  { text: "If you want to improve, be willing to be thought foolish.", author: "Epictetus", source: "Enchiridion" },
  { text: "Neither seek nor avoid; take what comes.", author: "Epictetus", source: "Enchiridion" },
  { text: "Small-minded people blame others. Average people blame themselves. The wise see all blame as foolishness.", author: "Epictetus", source: "Enchiridion" },
  { text: "A person\'s character is their destiny.", author: "Epictetus", source: "Discourses" },
  { text: "The beginning of philosophy is to know the condition of one\'s own mind.", author: "Epictetus", source: "Discourses" },
  { text: "Men are not disturbed by the things which happen, but by the opinions about the things.", author: "Epictetus", source: "Enchiridion" },
  { text: "Not what happens to you, but how you react to it is what matters.", author: "Epictetus", source: "Enchiridion" },
  { text: "Try to get what is your own. Don\'t cry for what is not.", author: "Epictetus", source: "Discourses" },
  { text: "He is a wise man who does not grieve for things he has not, but rejoices for those which he has.", author: "Epictetus", source: "Fragments" },
  { text: "The temple of our purest thoughts is silence.", author: "Epictetus", source: "Fragments" },
  { text: "Take heed that you do not play the part of an actor ill.", author: "Epictetus", source: "Enchiridion" },
  { text: "If you would be a reader, read; if a writer, write.", author: "Epictetus", source: "Discourses" },
  { text: "If you wish to be beautiful, practice beautiful deeds.", author: "Epictetus", source: "Discourses" },
  { text: "People are not disturbed by things, but by the view they take of them.", author: "Epictetus", source: "Enchiridion" },
  { text: "If a man knows not to which port he sails, no wind is favorable.", author: "Seneca", source: "Letters" },
  { text: "Cogita quam multos anni praeterierint. Think how many years have passed.", author: "Seneca", source: "Letters" },
  { text: "Invenies vitam brevem si omnia in illam congesseris. You will find life short if you crowd everything into it.", author: "Seneca", source: "Letters" },
  { text: "Tam debes alienos mores ferre quam tuos. You should bear others\' ways as you bear your own.", author: "Seneca", source: "Letters" },
  { text: "The willing are led by fate; the unwilling are dragged.", author: "Seneca", source: "Letters" },
  { text: "Omnes eodem cogimur. We are all driven to the same place.", author: "Seneca", source: "Letters" },
  { text: "Nihil aliud roga ab dis quam ut possint dare. Ask nothing of the gods but what they are able to give.", author: "Seneca", source: "Letters" },
  { text: "Where the disease is greatest, the physician is needed most.", author: "Seneca", source: "Letters" },
  { text: "One must cultivate one\'s garden.", author: "Seneca", source: "On Tranquility of Mind" },
  { text: "He who has injured you was either stronger or weaker than you.", author: "Seneca", source: "On Benefits" },
  { text: "You act like mortals in all that you fear, and like immortals in all that you desire.", author: "Seneca", source: "On the Shortness of Life" },
  { text: "The courage which looks danger in the face is far preferable to the courage which flies from it.", author: "Seneca", source: "Letters" },
  { text: "No wind is favorable to him who does not know where he is going.", author: "Seneca", source: "Letters" },
  { text: "Every hour comes to you precious and unique.", author: "Seneca", source: "Letters" },
  { text: "Nemo ad iudicium suum disertus est. No man is eloquent in his own cause.", author: "Seneca", source: "Letters" },
  { text: "Iniuriam qui facturus est iam facit. He who is going to do an injury is already doing it.", author: "Seneca", source: "Letters" },
  { text: "If you do not know to which harbor you are steering, no wind is favorable.", author: "Seneca", source: "Letters" },
  { text: "Otium sine litteris mors est et hominis vivi sepultura. Leisure without literature is death and burial of a living man.", author: "Seneca", source: "Letters" },
  { text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Seneca", source: "Letters" },
  { text: "Divide your time and cultivate it; otherwise nothing important gets done.", author: "Seneca", source: "Letters" },
  { text: "Nusquam est qui ubique est. He who is everywhere is nowhere.", author: "Seneca", source: "Letters" },
  { text: "Recede in te ipse quantum potes; cum his versare qui te meliorem acturi sunt.", author: "Seneca", source: "Letters" },
  { text: "Non refert quam multos libros habeas, sed quam bonos. It does not matter how many books you have, but how good they are.", author: "Seneca", source: "Letters" },
  { text: "Cogita quantum temporis absumpserit. Think how much time has been consumed.", author: "Seneca", source: "Letters" },
  { text: "Difficilis in praesentia philosophia est, sed mihi crede, hoc ipsum auxiliatur. Philosophy is difficult in practice, but believe me, this is its very help.", author: "Seneca", source: "Letters" },
  { text: "Vive ut victurus, para ut moriturus. Live as if you will live forever; prepare as if you will die tomorrow.", author: "Seneca", source: "Letters" },
  { text: "Nemo potest personam diu ferre. No one can wear a mask for long.", author: "Seneca", source: "Letters" },
  { text: "Nec quisquam bonus nisi qui simplex. None is good except the simple.", author: "Seneca", source: "Letters" },
  { text: "Qui philosophiam verus amat, nulli rei studentior esse debet quam bono animo. The true lover of philosophy should be more devoted to a good mind than to anything else.", author: "Seneca", source: "Letters" },
  { text: "Non progredi est regredi. Not to advance is to go back.", author: "Seneca", source: "Letters" },
  { text: "Dum differtur vita transcurrit. Life is lost while we delay.", author: "Seneca", source: "On the Shortness of Life" },
  { text: "Omnia aliena sunt, tempus tantum nostrum est. Everything is alien to us; time alone is ours.", author: "Seneca", source: "Letters" },
  { text: "Ita fac omnia, tamquam spectet aliquis bonus vir. Do everything as if some good man were watching.", author: "Seneca", source: "Letters" },
  { text: "Talis mihi semper animus meus videtur qualis me vidit. My mind always seems to me such as it appeared when it first saw me.", author: "Seneca", source: "Letters" },
  { text: "When you wake up in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "When you wake, tell yourself: today I shall meet with the busy-body, the thankless, arrogant, deceitful, envious, unsocial.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "What is not good for the swarm is not good for the bee.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Never esteem anything as of advantage that will make you break your word.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The first rule is to keep an untroubled spirit.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Nowhere can man find a quieter retreat than in his own soul.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "If someone is able to show me that I think or act wrongly, I will happily change.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Look back over the past and you can foresee the future.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Think not of what is lacking; think of what you have.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Your mind will take the shape of what you frequently hold in thought.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Wherever a man can live, there he can also live well.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Whatever the present moment contains, accept it as if you had chosen it.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Give yourself a gift: the present moment.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Everything in moderation, including moderation.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Execute every act of thy life as though it were thy last.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Be tolerant with others and strict with yourself.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Nothing happens to any man that he is not formed by nature to bear.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The present moment is all we ever have.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Dig within. Within is the wellspring of good; ever dig, and it will ever flow.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The first step: Don\'t be anxious. Nature controls it all.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The mark of a moderate man is freedom from his own ideas.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Very little is needed to make a happy life.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Perfection of character: to live each day as if it were your last.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The only wealth which you will keep forever is the wealth you have given away.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Be content to seem what you really are.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Anger cannot be dishonest.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Don\'t seek that all that happens should happen as you wish; but wish that everything that happens be as it is.", author: "Epictetus", source: "Enchiridion" },
  { text: "The world turns aside to let any man pass who knows where he is going.", author: "Epictetus", source: "Discourses" },
  { text: "There is only one way to happiness, and that is to cease worrying about things which are beyond the power of our will.", author: "Epictetus", source: "Discourses" },
  { text: "If you want to be a writer, write. If you want to be a reader, read.", author: "Epictetus", source: "Discourses" },
  { text: "Suffering arises from trying to control what is uncontrollable, or from neglecting what is within our power.", author: "Epictetus", source: "Enchiridion" },
  { text: "Freedom is not achieved by satisfying desire, but by eliminating it.", author: "Epictetus", source: "Discourses" },
  { text: "It is impossible for a man to learn what he thinks he already knows.", author: "Epictetus", source: "Discourses" },
  { text: "Either God wants to abolish evil and cannot; or he can but does not want to.", author: "Epictetus", source: "Discourses" },
  { text: "If you would cure anger, do not feed it. Say to yourself: \'I used to be angry every day; then every other day; then once in three days.\'", author: "Epictetus", source: "Enchiridion" },
  { text: "Progress is not achieved by luck or accident, but by working on yourself daily.", author: "Epictetus", source: "Discourses" },
  { text: "It is better to be in chains with friends, than to be in a garden with strangers.", author: "Epictetus", source: "Discourses" },
  { text: "The two powers which in my opinion constitute a wise man are those of bearing and forbearing.", author: "Epictetus", source: "Fragments" },
  { text: "Attach yourself to what is spiritually superior.", author: "Epictetus", source: "Enchiridion" },
  { text: "All philosophy lies in two words: sustain and abstain.", author: "Epictetus", source: "Fragments" },
  { text: "The greater the difficulty, the more glory in surmounting it.", author: "Epictetus", source: "Discourses" },
  { text: "He is wise who does not grieve for the things he has not, but rejoices for those which he has.", author: "Epictetus", source: "Fragments" },
  { text: "For it is not the things themselves which disturb men; for example, death is nothing terrible.", author: "Epictetus", source: "Enchiridion" },
  { text: "We should not moor a ship with one anchor.", author: "Epictetus", source: "Discourses" },
  { text: "Man is troubled not by events, but by the meaning he gives them.", author: "Epictetus", source: "Enchiridion" },
  { text: "Every habit and faculty is preserved and increased by correspondent actions.", author: "Epictetus", source: "Discourses" },
  { text: "The loftier the building, the deeper the foundation.", author: "Epictetus", source: "Discourses" },
  { text: "A ship ought not to be held by one anchor, nor life by a single hope.", author: "Epictetus", source: "Discourses" },
  { text: "Nothing outside of the will can hinder or harm the will; it can only harm itself.", author: "Epictetus", source: "Discourses" },
  { text: "You can bind up my leg, but not even Zeus has the power to break my freedom of choice.", author: "Epictetus", source: "Discourses" },
  { text: "Nature gave us one tongue and two ears so we could hear twice as much as we speak.", author: "Epictetus", source: "Fragments" },
  { text: "Man conquers the world by conquering himself.", author: "Zeno of Citium", source: "Fragments" },
  { text: "The goal of life is living in agreement with nature.", author: "Zeno of Citium", source: "Fragments" },
  { text: "Happiness is a good flow of life.", author: "Zeno of Citium", source: "Fragments" },
  { text: "We have two ears and one mouth, so we should listen more than we say.", author: "Zeno of Citium", source: "Fragments" },
  { text: "Steel your sensibilities, so that life shall hurt you as little as possible.", author: "Zeno of Citium", source: "Fragments" },
  { text: "Better to trip with the feet than with the tongue.", author: "Zeno of Citium", source: "Fragments" },
  { text: "No loss should be more regrettable to us than losing our time, for it\'s irretrievable.", author: "Zeno of Citium", source: "Fragments" },
  { text: "All things are parts of one single system, which is called nature.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Through perseverance many people win success out of what seemed destined to be failure.", author: "Zeno of Citium", source: "Fragments" },
  { text: "Do not indulge hope to the point of forgetting the present.", author: "Musonius Rufus", source: "Lectures" },
  { text: "The philosopher must heal himself before he attempts to heal others.", author: "Musonius Rufus", source: "Lectures" },
  { text: "It is not possible to live well today unless you treat it as your last day.", author: "Musonius Rufus", source: "Lectures" },
  { text: "Choose always the life that is most useful, and habit will render it the most agreeable.", author: "Musonius Rufus", source: "Lectures" },
  { text: "Those who have wisdom and love are the only ones who are rich.", author: "Musonius Rufus", source: "Lectures" },
  { text: "The person who seeks beauty will not find it; the person who seeks virtue will find beauty too.", author: "Musonius Rufus", source: "Lectures" },
  { text: "We suffer the punishment of those who wish to be gods; we are not content to live simply and justly.", author: "Musonius Rufus", source: "Lectures" },
  { text: "You should not be disturbed about having to deal with difficult people.", author: "Musonius Rufus", source: "Lectures" },
  { text: "Philosophy means taking care of oneself.", author: "Musonius Rufus", source: "Lectures" },
  { text: "To have good judgment, one must first have knowledge.", author: "Musonius Rufus", source: "Lectures" },
  { text: "The wise man does everything rightly.", author: "Chrysippus", source: "Fragments" },
  { text: "The goal of life is to live in accordance with reason.", author: "Chrysippus", source: "Fragments" },
  { text: "Virtue is the only true good.", author: "Chrysippus", source: "Fragments" },
  { text: "I begin to speak only when I\'m certain what I\'ll say isn\'t better left unsaid.", author: "Cato", source: "Fragments" },
  { text: "Grasp the subject, the words will follow.", author: "Cato", source: "Fragments" },
  { text: "Pardon one offense and you encourage the commission of many.", author: "Cato", source: "Fragments" },
  { text: "How long have you been putting off living?", author: "Seneca", source: "On the Shortness of Life" },
  { text: "While we teach, we learn.", author: "Seneca", source: "Letters" },
  { text: "The mind that is anxious about the future is miserable.", author: "Seneca", source: "Letters" },
  { text: "A gem cannot be polished without friction, nor a man perfected without trials.", author: "Seneca", source: "Letters" },
  { text: "There is no favorable wind for the sailor who doesn\'t know where to go.", author: "Seneca", source: "Letters" },
  { text: "You want to know what I\'ve been doing? I\'ve been keeping myself employed.", author: "Seneca", source: "Letters" },
  { text: "It is a rough road that leads to the heights of greatness.", author: "Seneca", source: "Letters" },
  { text: "Collect and save the time which has hitherto been cut into and stolen from you.", author: "Seneca", source: "Letters" },
  { text: "Limit yourself to the present.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Observe always that everything is the result of change.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "He who loves virtue for its own sake will never make sacrifices.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Whatever befalls thee was preordained for thee from eternity.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "That which is not good for the bee-hive cannot be good for the bees.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "How ridiculous and how strange to be surprised at anything which happens in life.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Understand at last that you have something in you more powerful and divine than what causes the bodily passions.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Within is the wellspring of good; ever dig, and it will ever flow.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The greatest obstacle to living is expectancy.", author: "Seneca", source: "On the Shortness of Life" },
  { text: "Treat yourself and others as an end, not as a means to an end.", author: "Seneca", source: "Letters" },
  { text: "What need is there to weep over parts of life? The whole of it calls for tears.", author: "Seneca", source: "On the Shortness of Life" },
  { text: "One of the most beautiful qualities of true friendship is to understand and to be understood.", author: "Seneca", source: "Letters" },
  { text: "It is not the man who has little, but the man who craves more, that is poor.", author: "Seneca", source: "Letters" },
  { text: "To wish to be well is a part of becoming well.", author: "Seneca", source: "Letters" },
  { text: "He who spends time regretting the past loses the present and risks the future.", author: "Seneca", source: "Letters" },
  { text: "Life is long if you know how to use it.", author: "Seneca", source: "On the Shortness of Life" },
  { text: "The formula for success is to use what you have, and not to use what you have not.", author: "Seneca", source: "Letters" },
  { text: "Courage leads to heaven; fear leads to death.", author: "Seneca", source: "Letters" },
  { text: "Nothing is burdensome if taken lightly.", author: "Seneca", source: "Letters" },
  { text: "Whatever you do, do it with all your might.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Begin. To begin is half the work. Let half still remain. Again begin this, and thou wilt have finished.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Think not of missing the target; think of the mark you make.", author: "Epictetus", source: "Discourses" },
  { text: "The sun also rises for the wicked.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The measure of a man is what he does with power.", author: "Epictetus", source: "Discourses" },
  { text: "If you realize that all things change, there is nothing you will try to hold on to.", author: "Epictetus", source: "Discourses" },
  { text: "Do not seek to have events happen as you want them to, but instead want them to happen as they do happen.", author: "Epictetus", source: "Enchiridion" },
  { text: "Take what you are given.", author: "Epictetus", source: "Enchiridion" },
  { text: "Act well your given part.", author: "Epictetus", source: "Enchiridion" },
  { text: "Do not seek to bring things to pass in accordance with your wishes, but wish for them as they are.", author: "Epictetus", source: "Enchiridion" },
  { text: "You were sick, and now you are well. This is health.", author: "Epictetus", source: "Discourses" },
  { text: "Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "A man\'s life is but a moment; his existence a flux.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The memory of everything is very soon overwhelmed in time.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Never let the same sin get you twice.", author: "Seneca", source: "Letters" },
  { text: "Better a wise enemy than a foolish friend.", author: "Seneca", source: "Letters" },
  { text: "The life we receive is not short, but we make it so, nor do we lack in it, but are wasteful of it.", author: "Seneca", source: "On the Shortness of Life" },
  { text: "How much better to persist in poverty than to make an unworthy profit.", author: "Seneca", source: "Letters" },
  { text: "Not he who has little, but he who wishes for more, is poor.", author: "Seneca", source: "Letters" },
  { text: "Do not be ashamed of needing help. You have a duty to fulfill just like a soldier on the wall of battle.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "If what you hold to be best is to be found in yourself — in your thoughts — why are you troubled?", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Think of the life you have lived until now as over and, as a dead man, see what\'s left as a bonus.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Everything — a horse, a vine — is created for some duty. For what task, then, were you yourself created?", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Conduct your life according to truth.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "If you do not wish to be prone to anger, do not feed the habit.", author: "Epictetus", source: "Discourses" },
  { text: "Apply yourself not to passivity, but to excellence.", author: "Epictetus", source: "Discourses" },
  { text: "Either pain or pleasure will master you; make sure it is the good one.", author: "Epictetus", source: "Discourses" },
  { text: "You have made the journey; you have wasted nothing.", author: "Epictetus", source: "Discourses" },
  { text: "No man who loves his country will ask what it needs of him.", author: "Epictetus", source: "Discourses" },
  { text: "Think about your opinions in the morning before doing anything.", author: "Epictetus", source: "Enchiridion" },
  { text: "Philosophy is first concerned with keeping the ruling faculty without violence.", author: "Epictetus", source: "Discourses" },
  { text: "The difficulty of this practice is not in the knowing but in the doing.", author: "Epictetus", source: "Discourses" },
  { text: "Men seek retreats for themselves — houses in the country, seashores, and mountains. But this is altogether a mark of the most common sort of men.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Consider how much more often you suffer from your anger and grief than from those very things for which you are angry and grieved.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "It never troubles the wolf how many the sheep may be.", author: "Virgil", source: "Eclogues" },
  { text: "Time is a river, a violent current of events, glimpsed once and already carried past us.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Keep in mind that it is not he who gives abuse or blows who affronts, but the view we take of these things as insulting.", author: "Epictetus", source: "Enchiridion" },
  { text: "Men are not moved by things, but by their opinions of things.", author: "Epictetus", source: "Enchiridion" },
  { text: "If you would not have a man flinch when the crisis comes, train him before it comes.", author: "Seneca", source: "Letters" },
  { text: "You are your own temple.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Begin at once to live, and count each day as a separate life.", author: "Seneca", source: "Letters" },
  { text: "To learn how to die is to unlearn how to be a slave.", author: "Seneca", source: "Letters" },
  { text: "He has the most who is most content with the least.", author: "Diogenes", source: "Fragments" },
  { text: "Know thyself.", author: "Socrates", source: "Fragments" },
  { text: "The unexamined life is not worth living.", author: "Socrates", source: "Apology" },
  { text: "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.", author: "Socrates", source: "Fragments" },
  { text: "I know that I know nothing.", author: "Socrates", source: "Fragments" },
  { text: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", author: "Socrates", source: "Fragments" },
  { text: "He who is not contented with what he has would not be contented with what he would like to have.", author: "Socrates", source: "Fragments" },
  { text: "Employ your time in improving yourself by other men\'s writings.", author: "Socrates", source: "Fragments" },
  { text: "Beware the barrenness of a busy life.", author: "Socrates", source: "Fragments" },
  { text: "Think not those faithful who praise all thy words and actions; but those who kindly reprove thy faults.", author: "Socrates", source: "Fragments" },
  { text: "Do not do to others what angers you if done to you by others.", author: "Socrates", source: "Fragments" },
  { text: "Be kind, for everyone you meet is fighting a harder battle.", author: "Socrates", source: "Fragments" },
  { text: "Wonder is the beginning of wisdom.", author: "Socrates", source: "Fragments" },
  { text: "He who is unable to live in society, or who has no need because he is sufficient for himself, must be either a beast or a god.", author: "Aristotle", source: "Politics" },
  { text: "Happiness is the meaning and the purpose of life, the whole aim and end of human existence.", author: "Aristotle", source: "Nicomachean Ethics" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", source: "Nicomachean Ethics" },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle", source: "Nicomachean Ethics" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", source: "Fragments" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", source: "Fragments" },
  { text: "Pleasure in the job puts perfection in the work.", author: "Aristotle", source: "Nicomachean Ethics" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle", source: "Nicomachean Ethics" },
  { text: "Courage is the first of human qualities because it is the quality which guarantees the others.", author: "Aristotle", source: "Nicomachean Ethics" },
  { text: "Excellence is never an accident; it is the result of high intention, sincere effort, intelligent direction, skillful execution.", author: "Aristotle", source: "Nicomachean Ethics" },
  { text: "The energy of the mind is the essence of life.", author: "Aristotle", source: "De Anima" },
  { text: "To perceive is to suffer.", author: "Aristotle", source: "De Anima" },
  { text: "The least initial deviation from the truth is multiplied later a thousandfold.", author: "Aristotle", source: "Fragments" },
  { text: "Poverty is the parent of revolution and crime.", author: "Aristotle", source: "Politics" },
  { text: "What is a friend? A single soul dwelling in two bodies.", author: "Aristotle", source: "Fragments" },
  { text: "Without friends no one would choose to live, though he had all other goods.", author: "Aristotle", source: "Nicomachean Ethics" },
  { text: "The high-minded man must care more for truth than for what people think.", author: "Aristotle", source: "Nicomachean Ethics" },
  { text: "Those who educate children well are more to be honored than they who produce them.", author: "Aristotle", source: "Fragments" },
  { text: "Well begun is half done.", author: "Aristotle", source: "Politics" },
  { text: "To run away from trouble is a form of cowardice.", author: "Aristotle", source: "Nicomachean Ethics" },
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "It is not death that a man should fear, but he should fear never beginning to live.", author: "Marcus Aurelius", source: "Meditations" },
];

export const eveningQuotes = [
  { text: "Let us prepare our minds as if we had come to the very end of life.", author: "Seneca", source: "Letters" },
  { text: "Ask yourself at day's end: What was ill done? What done? What left undone?", author: "Epictetus", source: "Discourses" },
  { text: "Perfection of character is this: to live each day as if it were your last.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "I have lived. The course which Fortune set for me is finished.", author: "Seneca", source: "Letters" },
  { text: "Examine what you have done today — not with pride, but with honesty.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Sleep is a daily reminder that we can let go.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Today I escaped anxiety. Or no, I discarded it, because it was within me.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", author: "Marcus Aurelius", source: "Meditations" },
];

export const mementoMoriQuotes = [
  { text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Think of yourself as dead. You have lived your life. Now take what's left and live it properly.", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Let us postpone nothing. Let us balance life's books each day.", author: "Seneca", source: "Letters" },
  { text: "The person who fears death will never do anything worth doing.", author: "Seneca", source: "Letters" },
  { text: "How many have laid waste to your life when you were unaware of what you were losing?", author: "Seneca", source: "On the Shortness of Life" },
  { text: "It is not that we have a short time to live, but that we waste a good deal of it.", author: "Seneca", source: "On the Shortness of Life" },
  { text: "Death is not an evil. What is it then? The one law mankind has that is free of all discrimination.", author: "Seneca", source: "Letters" },
  { text: "Perfecting yourself is the foundation of perfecting everything else.", author: "Epictetus", source: "Discourses" },
  { text: "This day will not come again. What will you make of the hours you are given?", author: "Marcus Aurelius", source: "Meditations" },
  { text: "Did you live well today? Not perfectly — but with intention?", author: "Marcus Aurelius", source: "Meditations" },
];

export function getDailyQuote(pool, offset = 0) {
  const today = new Date();
  const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 86400000);
  return pool[(dayOfYear + offset) % pool.length];
}