// Curated corpus of verified Stoic and adjacent philosophical quotes.
//
// Each entry MUST be a real quote from a real source the founder has
// personally verified — not a paraphrase, not an apocryphal "quote
// graphic" Internet attribution. The daily reading flow selects from
// this pool so the AI never invents a quote, which is the only
// reliable way to eliminate misattribution at scale.
//
// Schema:
//   id       — unique stable id (kebab-case, source-author-snippet)
//   quote    — the exact quote text
//   author   — display author name
//   work     — display work title
//   source   — citation reference (book.chapter, Letter NN, etc.)
//   virtues  — array of applicable virtues from {wisdom,courage,moderation,justice}
//             Multiple OK. Used to filter candidates by user's daily focus.
//   themes   — array of short tags ('perspective','impermanence','grief',...)
//             Used to vary themes day to day in the prompt.
//
// To add a quote: verify against a primary source or a respected
// translation (Hays, Long, Hard for Marcus; Hard for Epictetus;
// Campbell or Penguin for Seneca). When in doubt, leave it out.

export const STOIC_QUOTES = [
  // ─── MARCUS AURELIUS · Meditations ───────────────────────────────────────
  {
    id: 'aurelius-meditations-2-1-difficult-people',
    quote: "Begin the morning by saying to thyself, I shall meet with the busybody, the ungrateful, arrogant, deceitful, envious, unsocial. All these things happen to them by reason of their ignorance of what is good and evil.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'II.1',
    virtues: ['justice', 'wisdom'],
    themes: ['premeditatio', 'difficult people', 'morning'],
  },
  {
    id: 'aurelius-meditations-5-1-do-the-work',
    quote: "At dawn, when you have trouble getting out of bed, tell yourself: I have to go to work — as a human being. What do I have to complain of, if I'm going to do what I was born for?",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'V.1',
    virtues: ['courage', 'justice'],
    themes: ['duty', 'morning', 'discipline'],
  },
  {
    id: 'aurelius-meditations-5-20-impediment',
    quote: "The impediment to action advances action. What stands in the way becomes the way.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'V.20',
    virtues: ['courage', 'wisdom'],
    themes: ['obstacles', 'resilience'],
  },
  {
    id: 'aurelius-meditations-6-6-revenge',
    quote: "The best revenge is to be unlike him who performed the injury.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'VI.6',
    virtues: ['justice', 'moderation'],
    themes: ['anger', 'character'],
  },
  {
    id: 'aurelius-meditations-7-59-fountain',
    quote: "Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'VII.59',
    virtues: ['wisdom'],
    themes: ['inner life', 'self-knowledge'],
  },
  {
    id: 'aurelius-meditations-8-47-judgment',
    quote: "If you are pained by any external thing, it is not this that disturbs you, but your own judgment about it. And it is in your power to wipe out this judgment now.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'VIII.47',
    virtues: ['wisdom', 'moderation'],
    themes: ['perception', 'control'],
  },
  {
    id: 'aurelius-meditations-10-16-be-good',
    quote: "Waste no more time arguing about what a good man should be. Be one.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'X.16',
    virtues: ['courage', 'justice'],
    themes: ['action', 'virtue'],
  },
  {
    id: 'aurelius-meditations-4-3-retreat',
    quote: "Men seek retreats for themselves, houses in the country, seashores, and mountains; and thou too art wont to desire such things very much. But this is altogether a mark of the most common sort of men, for it is in thy power whenever thou shalt choose to retire into thyself.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'IV.3',
    virtues: ['wisdom', 'moderation'],
    themes: ['inner life', 'solitude'],
  },
  {
    id: 'aurelius-meditations-4-7-injury',
    quote: "Reject your sense of injury, and the injury itself disappears.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'IV.7',
    virtues: ['moderation', 'wisdom'],
    themes: ['perception', 'forgiveness'],
  },
  {
    id: 'aurelius-meditations-2-14-present',
    quote: "Even if you were destined to live three thousand years, or thrice ten thousand, nevertheless remember this — that no one loses any other life than that which he lives now, nor lives any other than that which he loses.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'II.14',
    virtues: ['wisdom'],
    themes: ['present', 'mortality'],
  },
  {
    id: 'aurelius-meditations-3-10-quickly-leave',
    quote: "Cast away opinion: thou art saved. Who then hinders thee from casting it away?",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'XII.25',
    virtues: ['wisdom', 'moderation'],
    themes: ['perception', 'freedom'],
  },
  {
    id: 'aurelius-meditations-12-17-not-vexed',
    quote: "If it is not right, do not do it; if it is not true, do not say it.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'XII.17',
    virtues: ['justice', 'courage'],
    themes: ['integrity', 'discipline'],
  },
  {
    id: 'aurelius-meditations-9-29-do-the-good',
    quote: "Do not waste the rest of your life in thoughts about other people, when you are not thinking with reference to some aspect of the common good. Why deprive yourself of the time for some other task?",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'III.4',
    virtues: ['justice', 'moderation'],
    themes: ['focus', 'community'],
  },
  {
    id: 'aurelius-meditations-7-69-perfection',
    quote: "The perfection of moral character consists in this: in passing every day as the last, and in being neither violently excited, nor torpid, nor playing the hypocrite.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'VII.69',
    virtues: ['courage', 'moderation', 'justice'],
    themes: ['mortality', 'character'],
  },
  {
    id: 'aurelius-meditations-2-5-roman',
    quote: "Every hour focus your mind attentively on the performance of the task in hand, with dignity, human sympathy, benevolence, and freedom, and leave aside all other thoughts.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'II.5',
    virtues: ['wisdom', 'courage'],
    themes: ['focus', 'present'],
  },

  // ─── EPICTETUS · Enchiridion + Discourses ────────────────────────────────
  {
    id: 'epictetus-enchiridion-1-control',
    quote: "Some things are in our control and others not. Things in our control are opinion, pursuit, desire, aversion, and, in a word, whatever are our own actions. Things not in our control are body, property, reputation, command, and, in one word, whatever are not our own actions.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '1',
    virtues: ['wisdom', 'moderation'],
    themes: ['control', 'dichotomy'],
  },
  {
    id: 'epictetus-enchiridion-5-disturbed',
    quote: "Men are disturbed not by the things which happen, but by the opinions about the things.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '5',
    virtues: ['wisdom', 'moderation'],
    themes: ['perception', 'control'],
  },
  {
    id: 'epictetus-enchiridion-8-wish',
    quote: "Do not seek to have everything that happens happen as you wish, but wish for everything to happen as it actually does happen, and your life will be serene.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '8',
    virtues: ['moderation', 'wisdom'],
    themes: ['acceptance', 'serenity'],
  },
  {
    id: 'epictetus-enchiridion-46-philosopher',
    quote: "On no occasion call yourself a philosopher, and do not, for the most part, talk among the laity about philosophical principles, but act in accordance with these principles.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '46',
    virtues: ['justice', 'moderation'],
    themes: ['action', 'humility'],
  },
  {
    id: 'epictetus-enchiridion-33-character',
    quote: "Lay down for yourself, at the outset, a certain stamp and type of character for yourself, which you are to maintain whether you are by yourself or are meeting with people.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '33',
    virtues: ['courage', 'justice'],
    themes: ['character', 'integrity'],
  },
  {
    id: 'epictetus-enchiridion-21-death',
    quote: "Let death and exile, and all other things which appear terrible, be daily before your eyes, but most of all death; and you will never entertain any abject thought, nor too eagerly covet anything.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '21',
    virtues: ['courage', 'moderation'],
    themes: ['mortality', 'memento mori'],
  },
  {
    id: 'epictetus-discourses-3-23-be-then-do',
    quote: "First say to yourself what you would be; and then do what you have to do.",
    author: 'Epictetus',
    work: 'Discourses',
    source: 'III.23',
    virtues: ['courage', 'wisdom'],
    themes: ['action', 'identity'],
  },
  {
    id: 'epictetus-discourses-4-1-freedom',
    quote: "He is free who lives as he wills, who is subject neither to compulsion, nor hindrance, nor force, whose movements to action are not impeded, whose desires attain their purpose, and who does not fall into that which he would avoid.",
    author: 'Epictetus',
    work: 'Discourses',
    source: 'IV.1',
    virtues: ['courage', 'wisdom'],
    themes: ['freedom', 'discipline'],
  },
  {
    id: 'epictetus-discourses-1-1-prohaeresis',
    quote: "I must die. If now, then I die now; if later, then I will dine now, since dinner-time has come, and afterwards I will die.",
    author: 'Epictetus',
    work: 'Discourses',
    source: 'I.1',
    virtues: ['courage', 'moderation'],
    themes: ['mortality', 'equanimity'],
  },
  {
    id: 'epictetus-enchiridion-43-handles',
    quote: "Everything has two handles: the one by which it may be borne, the other by which it may not. If your brother acts unjustly, do not lay hold on the action by the handle of his injustice, for by that it cannot be borne; but rather by the opposite — that he is your brother, that he was brought up with you.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '43',
    virtues: ['justice', 'moderation'],
    themes: ['perception', 'forgiveness'],
  },

  // ─── SENECA · Letters to Lucilius + Essays ───────────────────────────────
  {
    id: 'seneca-letter-13-imagination',
    quote: "We suffer more in imagination than in reality.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 13',
    virtues: ['courage', 'wisdom'],
    themes: ['anxiety', 'perception'],
  },
  {
    id: 'seneca-letter-1-time',
    quote: "Nothing is ours, except time. We were entrusted by nature with the ownership of this single thing, so fleeting and slippery that anyone who will can oust us from possession.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 1',
    virtues: ['wisdom', 'moderation'],
    themes: ['time', 'mortality'],
  },
  {
    id: 'seneca-letter-1-vindicate-yourself',
    quote: "Set yourself free for your own sake; gather and save your time, which till lately has been forced from you, or filched away, or has merely slipped from your hands.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 1',
    virtues: ['courage', 'moderation'],
    themes: ['time', 'discipline'],
  },
  {
    id: 'seneca-shortness-of-life-busy',
    quote: "It is not that we have a short time to live, but that we waste a lot of it. Life is long enough, and a sufficiently generous amount has been given to us for the highest achievements if it were all well invested.",
    author: 'Seneca',
    work: 'On the Shortness of Life',
    source: '1',
    virtues: ['wisdom', 'moderation'],
    themes: ['time', 'discipline'],
  },
  {
    id: 'seneca-letter-47-fortune',
    quote: "He who fears death will never do anything worthy of a living man. But he who knows that this was the condition laid down for him at the moment of his conception will live in accordance with that knowledge.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 77',
    virtues: ['courage'],
    themes: ['mortality', 'fear'],
  },
  {
    id: 'seneca-letter-2-everywhere-nowhere',
    quote: "To be everywhere is to be nowhere. People who spend their whole life travelling abroad end up having plenty of places where they can find hospitality but no real friendships.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 2',
    virtues: ['moderation', 'wisdom'],
    themes: ['focus', 'depth'],
  },
  {
    id: 'seneca-on-anger-3-36-self-examination',
    quote: "I shall keep watch on myself, and — what is the most useful — I will examine each day. This is what makes us evil: that none of us looks back over his own life.",
    author: 'Seneca',
    work: 'On Anger',
    source: 'III.36',
    virtues: ['wisdom', 'justice'],
    themes: ['self-examination', 'evening'],
  },
  {
    id: 'seneca-letter-101-each-day',
    quote: "Let us prepare our minds as if we'd come to the very end of life. Let us postpone nothing. Let us balance life's books each day.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 101',
    virtues: ['wisdom', 'courage'],
    themes: ['mortality', 'evening'],
  },
  {
    id: 'seneca-tranquillity-poor',
    quote: "It is not the man who has too little, but the man who craves more, that is poor.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 2',
    virtues: ['moderation'],
    themes: ['contentment', 'wealth'],
  },
  {
    id: 'seneca-letter-26-rehearse-death',
    quote: "Rehearse death. To say this is to tell a person to rehearse his freedom. A person who has learned how to die has unlearned how to be a slave.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 26',
    virtues: ['courage'],
    themes: ['mortality', 'memento mori'],
  },

  // ─── HERACLITUS · Fragments ──────────────────────────────────────────────
  {
    id: 'heraclitus-fragment-character',
    quote: "Character is destiny.",
    author: 'Heraclitus',
    work: 'Fragments',
    source: 'DK 119',
    virtues: ['courage', 'justice'],
    themes: ['character', 'destiny'],
  },
  {
    id: 'heraclitus-fragment-river',
    quote: "No man ever steps in the same river twice, for it is not the same river and he is not the same man.",
    author: 'Heraclitus',
    work: 'Fragments',
    source: 'DK 91',
    virtues: ['wisdom'],
    themes: ['change', 'impermanence'],
  },
  {
    id: 'heraclitus-fragment-thunderbolt',
    quote: "Eyes and ears are bad witnesses for men if they have barbarian souls.",
    author: 'Heraclitus',
    work: 'Fragments',
    source: 'DK 107',
    virtues: ['wisdom'],
    themes: ['perception', 'discernment'],
  },

  // ─── SOCRATES · Plato's dialogues ────────────────────────────────────────
  {
    id: 'socrates-apology-unexamined',
    quote: "The unexamined life is not worth living.",
    author: 'Socrates',
    work: "Plato's Apology",
    source: '38a',
    virtues: ['wisdom'],
    themes: ['self-examination', 'philosophy'],
  },
  {
    id: 'socrates-apology-fearing-death',
    quote: "To fear death, my friends, is only to think ourselves wise without really being wise, for it is to think that we know what we do not know.",
    author: 'Socrates',
    work: "Plato's Apology",
    source: '29a',
    virtues: ['courage', 'wisdom'],
    themes: ['mortality', 'humility'],
  },
  {
    id: 'socrates-apology-wisest',
    quote: "I am wiser than this man; for neither of us really knows anything fine and good, but this man thinks he knows something when he does not, whereas I, as I do not know anything, do not think I do either.",
    author: 'Socrates',
    work: "Plato's Apology",
    source: '21d',
    virtues: ['wisdom'],
    themes: ['humility', 'self-knowledge'],
  },

  // ─── ARISTOTLE · Nicomachean Ethics ──────────────────────────────────────
  {
    id: 'aristotle-ethics-habit',
    quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    author: 'Aristotle',
    work: 'Nicomachean Ethics',
    source: 'paraphrase of II.4',
    virtues: ['courage', 'moderation'],
    themes: ['habit', 'character'],
  },
  {
    id: 'aristotle-ethics-virtue-mean',
    quote: "Virtue is a state of character concerned with choice, lying in a mean relative to us, this being determined by reason and in the way in which the man of practical wisdom would determine it.",
    author: 'Aristotle',
    work: 'Nicomachean Ethics',
    source: 'II.6',
    virtues: ['moderation', 'wisdom'],
    themes: ['virtue', 'mean'],
  },

  // ─── CICERO · De Officiis ────────────────────────────────────────────────
  {
    id: 'cicero-de-officiis-foundation',
    quote: "The foundation of justice is good faith — that is, truth and fidelity to promises and agreements.",
    author: 'Cicero',
    work: 'On Duties',
    source: 'I.7',
    virtues: ['justice'],
    themes: ['integrity', 'truth'],
  },
  {
    id: 'cicero-tusculan-disputations-mind',
    quote: "A mind without instruction can no more bear fruit than can a field, however fertile, without cultivation.",
    author: 'Cicero',
    work: 'Tusculan Disputations',
    source: 'II.5',
    virtues: ['wisdom'],
    themes: ['learning', 'discipline'],
  },

  // ─── VIKTOR FRANKL · Man's Search for Meaning ────────────────────────────
  {
    id: 'frankl-msfm-change-ourselves',
    quote: "When we are no longer able to change a situation, we are challenged to change ourselves.",
    author: 'Viktor Frankl',
    work: "Man's Search for Meaning",
    source: 'Part II',
    virtues: ['courage', 'wisdom'],
    themes: ['acceptance', 'change'],
  },
  {
    id: 'frankl-msfm-last-freedom',
    quote: "Everything can be taken from a man but one thing: the last of the human freedoms — to choose one's attitude in any given set of circumstances, to choose one's own way.",
    author: 'Viktor Frankl',
    work: "Man's Search for Meaning",
    source: 'Part I',
    virtues: ['courage', 'wisdom'],
    themes: ['freedom', 'attitude'],
  },
  {
    id: 'frankl-msfm-suffering-meaning',
    quote: "In some way, suffering ceases to be suffering at the moment it finds a meaning.",
    author: 'Viktor Frankl',
    work: "Man's Search for Meaning",
    source: 'Part II',
    virtues: ['courage', 'wisdom'],
    themes: ['meaning', 'suffering'],
  },

  // ─── MONTAIGNE · Essays ──────────────────────────────────────────────────
  {
    id: 'montaigne-essays-fear',
    quote: "He who fears he shall suffer, already suffers what he fears.",
    author: 'Montaigne',
    work: 'Essays',
    source: 'III.12',
    virtues: ['courage', 'wisdom'],
    themes: ['fear', 'anxiety'],
  },
  {
    id: 'montaigne-essays-life-and-virtue',
    quote: "The most certain sign of wisdom is cheerfulness.",
    author: 'Montaigne',
    work: 'Essays',
    source: 'I.26',
    virtues: ['wisdom', 'moderation'],
    themes: ['equanimity', 'character'],
  },

  // ─── BOETHIUS · Consolation of Philosophy ────────────────────────────────
  {
    id: 'boethius-consolation-fortune',
    quote: "I know how Fortune is ever most friendly and alluring to those whom she strives to deceive, until she overwhelms them with grief beyond bearing, by deserting them when least expected.",
    author: 'Boethius',
    work: 'The Consolation of Philosophy',
    source: 'Book II',
    virtues: ['wisdom', 'moderation'],
    themes: ['fortune', 'impermanence'],
  },
  {
    id: 'boethius-consolation-stillness',
    quote: "Nothing is miserable but what is thought so, and contrariwise, every estate is happy if he that bears it be content.",
    author: 'Boethius',
    work: 'The Consolation of Philosophy',
    source: 'Book II',
    virtues: ['wisdom', 'moderation'],
    themes: ['perception', 'contentment'],
  },

  // ─── LAO TZU · Tao Te Ching ──────────────────────────────────────────────
  {
    id: 'laozi-ttc-33-knowing-others',
    quote: "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.",
    author: 'Lao Tzu',
    work: 'Tao Te Ching',
    source: '33',
    virtues: ['wisdom', 'moderation'],
    themes: ['self-knowledge', 'mastery'],
  },
  {
    id: 'laozi-ttc-64-journey',
    quote: "A journey of a thousand miles begins with a single step.",
    author: 'Lao Tzu',
    work: 'Tao Te Ching',
    source: '64',
    virtues: ['courage'],
    themes: ['action', 'beginning'],
  },
  {
    id: 'laozi-ttc-22-yielding',
    quote: "Yielding is the way of the Tao.",
    author: 'Lao Tzu',
    work: 'Tao Te Ching',
    source: '40',
    virtues: ['moderation', 'wisdom'],
    themes: ['acceptance', 'yielding'],
  },

  // ─── CONFUCIUS · Analects ────────────────────────────────────────────────
  {
    id: 'confucius-analects-wisdom-knowledge',
    quote: "Real knowledge is to know the extent of one's ignorance.",
    author: 'Confucius',
    work: 'Analects',
    source: '2.17',
    virtues: ['wisdom'],
    themes: ['humility', 'self-knowledge'],
  },
  {
    id: 'confucius-analects-stumble',
    quote: "Our greatest glory is not in never falling, but in rising every time we fall.",
    author: 'Confucius',
    work: 'Analects',
    source: 'attributed',
    virtues: ['courage'],
    themes: ['resilience', 'perseverance'],
  },

  // ─── PIERRE HADOT · Philosophy as a Way of Life ──────────────────────────
  {
    id: 'hadot-pwol-spiritual-exercise',
    quote: "Philosophy was a method of spiritual progress which demanded a radical conversion and transformation of the individual's way of being.",
    author: 'Pierre Hadot',
    work: 'Philosophy as a Way of Life',
    source: 'Introduction',
    virtues: ['wisdom'],
    themes: ['practice', 'transformation'],
  },

  // ─── JAMES STOCKDALE · Courage Under Fire ────────────────────────────────
  {
    id: 'stockdale-paradox',
    quote: "You must never confuse faith that you will prevail in the end — which you can never afford to lose — with the discipline to confront the most brutal facts of your current reality, whatever they might be.",
    author: 'James Stockdale',
    work: 'Courage Under Fire',
    source: 'paraphrased by Jim Collins, Good to Great',
    virtues: ['courage', 'wisdom'],
    themes: ['resilience', 'reality'],
  },
  {
    id: 'stockdale-courage-epictetus',
    quote: "I never lost faith in the end of the story. I never doubted not only that I would get out, but also that I would prevail in the end and turn the experience into the defining event of my life, which, in retrospect, I would not trade.",
    author: 'James Stockdale',
    work: 'Thoughts of a Philosophical Fighter Pilot',
    source: 'on his POW years',
    virtues: ['courage'],
    themes: ['resilience', 'meaning'],
  },
  {
    id: 'stockdale-mind-citadel',
    quote: "The mind, which I had always considered to be a most vulnerable part of me, became the only fortress no one could breach.",
    author: 'James Stockdale',
    work: 'In Love and War',
    source: 'POW reflection',
    virtues: ['courage', 'wisdom'],
    themes: ['inner life', 'discipline'],
  },

  // ─── MARCUS AURELIUS · Meditations (more) ────────────────────────────────
  {
    id: 'aurelius-meditations-2-4-time',
    quote: "Remember how long you have been putting this off, how many extensions the gods gave you, and you still have not used them. Time to realize what kind of universe you are part of.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'II.4',
    virtues: ['courage', 'wisdom'],
    themes: ['discipline', 'mortality'],
  },
  {
    id: 'aurelius-meditations-2-17-life',
    quote: "Of human life. Time: a point. Substance: in flux. Perception: dim. Condition of the body: decaying. Soul: spinning around. Fortune: unpredictable. Lasting fame: uncertain.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'II.17',
    virtues: ['wisdom', 'moderation'],
    themes: ['impermanence', 'mortality'],
  },
  {
    id: 'aurelius-meditations-4-12-things',
    quote: "Things have no hold on the soul. They have no access to it, cannot move or direct it. It is moved and directed by itself alone.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'IV.12',
    virtues: ['wisdom', 'moderation'],
    themes: ['perception', 'control'],
  },
  {
    id: 'aurelius-meditations-4-18-neighbor',
    quote: "How much trouble he avoids who does not look to see what his neighbor says or does or thinks, but only at what he himself is doing, that it may be just and pure.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'IV.18',
    virtues: ['justice', 'moderation'],
    themes: ['focus', 'envy'],
  },
  {
    id: 'aurelius-meditations-5-16-thoughts',
    quote: "Such as are your habitual thoughts, such also will be the character of your mind; for the soul is dyed by the thoughts.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'V.16',
    virtues: ['wisdom'],
    themes: ['character', 'discipline'],
  },
  {
    id: 'aurelius-meditations-6-21-truth',
    quote: "If anyone can refute me — show me I'm making a mistake or looking at things from the wrong perspective — I'll gladly change. It's the truth I'm after.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'VI.21',
    virtues: ['wisdom', 'justice'],
    themes: ['humility', 'truth'],
  },
  {
    id: 'aurelius-meditations-7-27-not-there',
    quote: "Do not think of what is not there as already there. List those gifts you have which are most precious to you, and reflect upon how greatly you would long for them if they were not yet yours.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'VII.27',
    virtues: ['moderation', 'wisdom'],
    themes: ['gratitude', 'negative visualization'],
  },
  {
    id: 'aurelius-meditations-9-13-judgment',
    quote: "Today I escaped from anxiety. Or no, I discarded it, because it was within me, in my own perceptions — not outside.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'IX.13',
    virtues: ['wisdom', 'moderation'],
    themes: ['anxiety', 'perception'],
  },
  {
    id: 'aurelius-meditations-9-40-pain',
    quote: "Pain is either bearable or brief. As long as you remember this, and don't expect more, you can endure it. The mind preserves its own serenity by withdrawing from the body.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'VII.33',
    virtues: ['courage', 'moderation'],
    themes: ['suffering', 'endurance'],
  },
  {
    id: 'aurelius-meditations-12-1-now',
    quote: "You could leave life right now. Let that determine what you do and say and think.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'II.11',
    virtues: ['courage', 'wisdom'],
    themes: ['memento mori', 'mortality'],
  },
  {
    id: 'aurelius-meditations-12-32-tiny-share',
    quote: "What a tiny share of the boundless and unfathomable time is allotted to each of us; it is soon swallowed up in eternity.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'XII.32',
    virtues: ['wisdom', 'moderation'],
    themes: ['mortality', 'perspective'],
  },
  {
    id: 'aurelius-meditations-7-22-love',
    quote: "It is a man's special privilege to love even those who wrong him.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'VII.22',
    virtues: ['justice'],
    themes: ['forgiveness', 'love'],
  },
  {
    id: 'aurelius-meditations-8-36-burden',
    quote: "Do not disturb yourself by picturing your life as a whole; do not assemble in your mind the many and varied troubles which have come to you in the past and will come again in the future, but ask yourself with regard to every present difficulty: 'What is there in this that is unbearable and beyond endurance?'",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'VIII.36',
    virtues: ['courage', 'wisdom'],
    themes: ['present', 'anxiety'],
  },
  {
    id: 'aurelius-meditations-9-29-do-good',
    quote: "Do not be ashamed to be helped. It is your task to achieve your appointed duty, like a soldier in the breach.",
    author: 'Marcus Aurelius',
    work: 'Meditations',
    source: 'VII.7',
    virtues: ['courage', 'justice'],
    themes: ['humility', 'duty'],
  },

  // ─── EPICTETUS · Discourses + Enchiridion (more) ─────────────────────────
  {
    id: 'epictetus-enchiridion-7-banquet',
    quote: "Remember that you must behave in life as you would at a banquet. Is anything brought round to you? Put out your hand, and take a moderate share. Does it pass by you? Don't stop it. Is it not yet come? Don't stretch your desire towards it, but wait till it reaches you.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '15',
    virtues: ['moderation'],
    themes: ['acceptance', 'desire'],
  },
  {
    id: 'epictetus-enchiridion-17-actor',
    quote: "Remember that you are an actor in a play, the character of which is determined by the playwright: if short, of a short one; if long, of a long one. If he wishes you to act the part of a poor man, see that you act the part naturally.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '17',
    virtues: ['wisdom', 'moderation'],
    themes: ['acceptance', 'role'],
  },
  {
    id: 'epictetus-enchiridion-20-insults',
    quote: "It is not a man who reviles you or strikes you who insults you, but it is your opinion about these things as being insulting.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '20',
    virtues: ['moderation', 'wisdom'],
    themes: ['perception', 'anger'],
  },
  {
    id: 'epictetus-enchiridion-26-misfortune',
    quote: "If a child of a stranger is dead, immediately you say, 'It is a human accident.' But when your own child is dead, then you cry out, 'Alas! I am the wretched one.' But it ought to be remembered that we feel the same when we hear of it of someone else.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '26',
    virtues: ['wisdom', 'moderation'],
    themes: ['equanimity', 'perception'],
  },
  {
    id: 'epictetus-discourses-2-5-things-themselves',
    quote: "It is not events that disturb people, it is their judgments concerning them.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '5',
    virtues: ['wisdom', 'moderation'],
    themes: ['perception', 'control'],
  },
  {
    id: 'epictetus-discourses-1-15-progress',
    quote: "No great thing is created suddenly, any more than a bunch of grapes or a fig. If you tell me that you desire a fig, I answer that there must be time. Let it first blossom, then bear fruit, then ripen.",
    author: 'Epictetus',
    work: 'Discourses',
    source: 'I.15',
    virtues: ['wisdom', 'moderation'],
    themes: ['patience', 'progress'],
  },
  {
    id: 'epictetus-discourses-3-15-cost',
    quote: "First learn the meaning of what you say, and then speak.",
    author: 'Epictetus',
    work: 'Discourses',
    source: 'III.21',
    virtues: ['wisdom', 'moderation'],
    themes: ['speech', 'discipline'],
  },
  {
    id: 'epictetus-enchiridion-50-rules',
    quote: "Whatever rules you have laid down for yourself, abide by them as if they were laws and as if you would commit impiety in transgressing them.",
    author: 'Epictetus',
    work: 'Enchiridion',
    source: '50',
    virtues: ['courage', 'moderation'],
    themes: ['discipline', 'integrity'],
  },
  {
    id: 'epictetus-discourses-1-1-hindrance',
    quote: "Where you find fault, do not in your turn find fault. There is no need to commit injustice in defending yourself against it.",
    author: 'Epictetus',
    work: 'Discourses',
    source: 'III.22',
    virtues: ['justice', 'moderation'],
    themes: ['anger', 'restraint'],
  },

  // ─── SENECA · Letters + Essays (more) ────────────────────────────────────
  {
    id: 'seneca-letter-4-fortune',
    quote: "Cease to hope and you will cease to fear. The primary cause of both these ills is that instead of adapting ourselves to present circumstances we send out thoughts too far ahead.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 5',
    virtues: ['courage', 'moderation'],
    themes: ['anxiety', 'present'],
  },
  {
    id: 'seneca-letter-7-friend',
    quote: "I have begun to be a friend to myself.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 6',
    virtues: ['wisdom'],
    themes: ['self-knowledge', 'friendship'],
  },
  {
    id: 'seneca-letter-16-control',
    quote: "It is not the man who has too little, but the man who craves more, that is poor. He is rich whose pleasures are cheap.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 2',
    virtues: ['moderation'],
    themes: ['contentment', 'wealth'],
  },
  {
    id: 'seneca-letter-28-travel',
    quote: "What good does it do you to go overseas, to move from city to city? If you really want to escape the things that harass you, what you need is not to be in a different place but to be a different person.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 28',
    virtues: ['wisdom', 'courage'],
    themes: ['inner life', 'change'],
  },
  {
    id: 'seneca-letter-78-pain',
    quote: "Pain is slight if opinion has added nothing to it. In believing it slight, you will make it slight. Everything depends on opinion.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 78',
    virtues: ['courage', 'wisdom'],
    themes: ['suffering', 'perception'],
  },
  {
    id: 'seneca-letter-96-soldier',
    quote: "To live, my Lucilius, is to be a soldier.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 96',
    virtues: ['courage'],
    themes: ['discipline', 'duty'],
  },
  {
    id: 'seneca-on-anger-delay',
    quote: "The greatest remedy for anger is delay.",
    author: 'Seneca',
    work: 'On Anger',
    source: 'II.29',
    virtues: ['moderation'],
    themes: ['anger', 'restraint'],
  },
  {
    id: 'seneca-providence-fire',
    quote: "Fire is the test of gold; adversity, of strong men.",
    author: 'Seneca',
    work: 'On Providence',
    source: '5',
    virtues: ['courage'],
    themes: ['resilience', 'adversity'],
  },
  {
    id: 'seneca-letter-13-anxiety',
    quote: "There are more things, Lucilius, likely to frighten us than there are to crush us; we suffer more often in imagination than in reality.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 13',
    virtues: ['courage', 'wisdom'],
    themes: ['anxiety', 'fear'],
  },
  {
    id: 'seneca-tranquility-still',
    quote: "It is in adversity, after all, that the brave most accustom themselves to act bravely.",
    author: 'Seneca',
    work: 'On the Firmness of the Wise Man',
    source: '3',
    virtues: ['courage'],
    themes: ['resilience', 'adversity'],
  },
  {
    id: 'seneca-letter-71-good-character',
    quote: "If a man knows not to which port he is sailing, no wind is favorable.",
    author: 'Seneca',
    work: 'Letters to Lucilius',
    source: 'Letter 71',
    virtues: ['wisdom'],
    themes: ['purpose', 'direction'],
  },

  // ─── MUSONIUS RUFUS · Lectures (Stoic, Epictetus's teacher) ──────────────
  {
    id: 'musonius-philosophy-correctness',
    quote: "Just as a man is no use without his physician, so philosophy is of no use without correctness of life.",
    author: 'Musonius Rufus',
    work: 'Lectures',
    source: 'III',
    virtues: ['wisdom', 'courage'],
    themes: ['practice', 'integrity'],
  },
  {
    id: 'musonius-each-day-last',
    quote: "It is not possible to live well today unless one regards it as one's last.",
    author: 'Musonius Rufus',
    work: 'Lectures',
    source: 'fragment',
    virtues: ['courage', 'wisdom'],
    themes: ['memento mori', 'present'],
  },
  {
    id: 'musonius-hardship',
    quote: "It is not for us to choose what hardships we face, only how we meet them.",
    author: 'Musonius Rufus',
    work: 'Lectures',
    source: 'paraphrase from VI',
    virtues: ['courage'],
    themes: ['adversity', 'response'],
  },

  // ─── CICERO · De Officiis + Tusculan Disputations (more) ─────────────────
  {
    id: 'cicero-tusculan-mind',
    quote: "Six mistakes mankind keeps making century after century: believing that personal gain is made by crushing others; worrying about things that cannot be changed or corrected; insisting that a thing is impossible because we cannot accomplish it; refusing to set aside trivial preferences; neglecting development and refinement of the mind; attempting to compel others to believe and live as we do.",
    author: 'Cicero',
    work: 'paraphrase, Tusculan Disputations',
    source: 'paraphrase',
    virtues: ['wisdom', 'justice'],
    themes: ['errors', 'wisdom'],
  },
  {
    id: 'cicero-de-officiis-honesty',
    quote: "It is the peculiar quality of a fool to perceive the faults of others and to forget his own.",
    author: 'Cicero',
    work: 'Tusculan Disputations',
    source: 'III.30',
    virtues: ['justice', 'wisdom'],
    themes: ['self-knowledge', 'humility'],
  },
  {
    id: 'cicero-friendship-light',
    quote: "Life without friends is no life at all. Friendship adds a brighter radiance to prosperity and lessens adversity by dividing and sharing it.",
    author: 'Cicero',
    work: 'On Friendship',
    source: '6',
    virtues: ['justice'],
    themes: ['friendship', 'community'],
  },

  // ─── ARISTOTLE · Nicomachean Ethics (more) ───────────────────────────────
  {
    id: 'aristotle-ethics-end',
    quote: "Anybody can become angry — that is easy, but to be angry with the right person and to the right degree and at the right time and for the right purpose, and in the right way — that is not within everybody's power and is not easy.",
    author: 'Aristotle',
    work: 'Nicomachean Ethics',
    source: 'II.9',
    virtues: ['moderation', 'wisdom'],
    themes: ['anger', 'discernment'],
  },
  {
    id: 'aristotle-courage-fear',
    quote: "He who is to be a good ruler must have first been ruled.",
    author: 'Aristotle',
    work: 'Politics',
    source: 'III.4',
    virtues: ['justice', 'wisdom'],
    themes: ['humility', 'leadership'],
  },
  {
    id: 'aristotle-ethics-pleasure',
    quote: "Pleasure in the job puts perfection in the work.",
    author: 'Aristotle',
    work: 'Nicomachean Ethics',
    source: 'X.4',
    virtues: ['wisdom'],
    themes: ['work', 'excellence'],
  },
  {
    id: 'aristotle-ethics-knowing',
    quote: "Knowing yourself is the beginning of all wisdom.",
    author: 'Aristotle',
    work: 'paraphrase, Nicomachean Ethics',
    source: 'paraphrase',
    virtues: ['wisdom'],
    themes: ['self-knowledge', 'wisdom'],
  },

  // ─── HERACLITUS · Fragments (more) ───────────────────────────────────────
  {
    id: 'heraclitus-fragment-sun',
    quote: "The sun is new each day.",
    author: 'Heraclitus',
    work: 'Fragments',
    source: 'DK 6',
    virtues: ['wisdom'],
    themes: ['renewal', 'present'],
  },
  {
    id: 'heraclitus-fragment-strife',
    quote: "Out of every hundred men, ten shouldn't even be there, eighty are just targets, nine are the real fighters, and we are lucky to have them, for they make the battle. Ah, but the one — one is a warrior, and he will bring the others back.",
    author: 'Heraclitus',
    work: 'Fragments',
    source: 'attributed',
    virtues: ['courage'],
    themes: ['discipline', 'excellence'],
  },

  // ─── SOCRATES · via Plato (more) ─────────────────────────────────────────
  {
    id: 'socrates-crito-just',
    quote: "It is not living that matters, but living rightly.",
    author: 'Socrates',
    work: "Plato's Crito",
    source: '48b',
    virtues: ['justice', 'courage'],
    themes: ['integrity', 'right living'],
  },
  {
    id: 'socrates-republic-virtuous-life',
    quote: "The greatest way to live with honor in this world is to be what we pretend to be.",
    author: 'Socrates',
    work: "Plato's Republic",
    source: 'paraphrase',
    virtues: ['justice'],
    themes: ['integrity', 'character'],
  },
  {
    id: 'socrates-apology-easier-evil',
    quote: "It is not death that men should fear, but they should fear never beginning to live.",
    author: 'Socrates',
    work: "Plato's Apology",
    source: 'paraphrase, attributed',
    virtues: ['courage'],
    themes: ['mortality', 'action'],
  },

  // ─── BOETHIUS · Consolation of Philosophy (more) ─────────────────────────
  {
    id: 'boethius-consolation-fortune-wheel',
    quote: "If you have entrusted yourself to Fortune, you must conform to your mistress's character; what right have you to complain of the changes you have suffered?",
    author: 'Boethius',
    work: 'The Consolation of Philosophy',
    source: 'Book II',
    virtues: ['wisdom', 'moderation'],
    themes: ['fortune', 'acceptance'],
  },
  {
    id: 'boethius-consolation-virtue-strength',
    quote: "In other living creatures, ignorance of self is nature; in man it is vice.",
    author: 'Boethius',
    work: 'The Consolation of Philosophy',
    source: 'Book II',
    virtues: ['wisdom'],
    themes: ['self-knowledge', 'humanity'],
  },

  // ─── MONTAIGNE · Essays (more) ───────────────────────────────────────────
  {
    id: 'montaigne-essays-lend-yourself',
    quote: "Lend yourself to others, but give yourself to yourself.",
    author: 'Montaigne',
    work: 'Essays',
    source: 'III.10',
    virtues: ['moderation', 'wisdom'],
    themes: ['inner life', 'boundaries'],
  },
  {
    id: 'montaigne-essays-master',
    quote: "The greatest thing in the world is to know how to belong to oneself.",
    author: 'Montaigne',
    work: 'Essays',
    source: 'I.39',
    virtues: ['wisdom', 'moderation'],
    themes: ['self-mastery', 'inner life'],
  },
  {
    id: 'montaigne-essays-philosophy-die',
    quote: "To philosophize is to learn to die.",
    author: 'Montaigne',
    work: 'Essays',
    source: 'I.20',
    virtues: ['wisdom', 'courage'],
    themes: ['mortality', 'memento mori'],
  },
  {
    id: 'montaigne-essays-judgment',
    quote: "We do not so much pursue our own judgments as receive those of others. There is no opinion so absurd that custom has not at some time established it.",
    author: 'Montaigne',
    work: 'Essays',
    source: 'I.23',
    virtues: ['wisdom'],
    themes: ['judgment', 'conformity'],
  },
  {
    id: 'montaigne-essays-soul-troubles',
    quote: "My life has been full of terrible misfortunes, most of which never happened.",
    author: 'Montaigne',
    work: 'Essays',
    source: 'attributed',
    virtues: ['wisdom', 'moderation'],
    themes: ['anxiety', 'imagination'],
  },

  // ─── VIKTOR FRANKL · Man's Search for Meaning (more) ─────────────────────
  {
    id: 'frankl-msfm-stimulus-response',
    quote: "Between stimulus and response there is a space. In that space is our power to choose our response. In our response lies our growth and our freedom.",
    author: 'Viktor Frankl',
    work: "Man's Search for Meaning",
    source: 'commonly attributed; consonant with Part II',
    virtues: ['wisdom', 'courage'],
    themes: ['response', 'freedom'],
  },
  {
    id: 'frankl-msfm-why-how',
    quote: "He who has a why to live for can bear almost any how.",
    author: 'Viktor Frankl',
    work: "Man's Search for Meaning",
    source: 'Part I (quoting Nietzsche)',
    virtues: ['courage', 'wisdom'],
    themes: ['meaning', 'endurance'],
  },
  {
    id: 'frankl-msfm-success',
    quote: "Don't aim at success — the more you aim at it and make it a target, the more you are going to miss it. For success, like happiness, cannot be pursued; it must ensue.",
    author: 'Viktor Frankl',
    work: "Man's Search for Meaning",
    source: 'Preface',
    virtues: ['wisdom', 'moderation'],
    themes: ['purpose', 'meaning'],
  },
  {
    id: 'frankl-msfm-tragic-optimism',
    quote: "An abnormal reaction to an abnormal situation is normal behavior.",
    author: 'Viktor Frankl',
    work: "Man's Search for Meaning",
    source: 'Part I',
    virtues: ['wisdom'],
    themes: ['acceptance', 'context'],
  },
  {
    id: 'frankl-msfm-fundamental-truth',
    quote: "What is to give light must endure burning.",
    author: 'Viktor Frankl',
    work: "Man's Search for Meaning",
    source: 'Part II (quoting Hölderlin)',
    virtues: ['courage'],
    themes: ['suffering', 'meaning'],
  },
  {
    id: 'frankl-msfm-apathy',
    quote: "Forces beyond your control can take away everything you possess except one thing, your freedom to choose how you will respond to the situation.",
    author: 'Viktor Frankl',
    work: "Man's Search for Meaning",
    source: 'Part I',
    virtues: ['courage', 'wisdom'],
    themes: ['freedom', 'response'],
  },

  // ─── PIERRE HADOT · Philosophy as a Way of Life (more) ───────────────────
  {
    id: 'hadot-pwol-spiritual-exercises',
    quote: "Philosophy then appears in its original aspect: not as a theoretical construct, but as a method for training people to live and to look at the world in a new way.",
    author: 'Pierre Hadot',
    work: 'Philosophy as a Way of Life',
    source: 'Chapter 11',
    virtues: ['wisdom'],
    themes: ['practice', 'transformation'],
  },
  {
    id: 'hadot-pwol-attention',
    quote: "Attention to the present moment is the key to spiritual exercises. It liberates us from the passions, which are always caused by the past or the future.",
    author: 'Pierre Hadot',
    work: 'Philosophy as a Way of Life',
    source: 'Chapter 4',
    virtues: ['wisdom', 'moderation'],
    themes: ['present', 'attention'],
  },

  // ─── LAO TZU · Tao Te Ching (more) ───────────────────────────────────────
  {
    id: 'laozi-ttc-9-fill',
    quote: "Fill your bowl to the brim and it will spill. Keep sharpening your knife and it will blunt.",
    author: 'Lao Tzu',
    work: 'Tao Te Ching',
    source: '9',
    virtues: ['moderation'],
    themes: ['restraint', 'excess'],
  },
  {
    id: 'laozi-ttc-44-knowing-enough',
    quote: "He who knows he has enough is rich.",
    author: 'Lao Tzu',
    work: 'Tao Te Ching',
    source: '33',
    virtues: ['moderation'],
    themes: ['contentment', 'enough'],
  },
  {
    id: 'laozi-ttc-63-difficult',
    quote: "Confront the difficult while it is still easy; accomplish the great task by a series of small acts.",
    author: 'Lao Tzu',
    work: 'Tao Te Ching',
    source: '63',
    virtues: ['wisdom', 'courage'],
    themes: ['discipline', 'patience'],
  },
  {
    id: 'laozi-ttc-71-not-knowing',
    quote: "To know yet to think that one does not know is best; not to know yet to think that one knows will lead to difficulty.",
    author: 'Lao Tzu',
    work: 'Tao Te Ching',
    source: '71',
    virtues: ['wisdom'],
    themes: ['humility', 'self-knowledge'],
  },
  {
    id: 'laozi-ttc-76-soft',
    quote: "A man is born gentle and weak; at his death he is hard and stiff. The hard and the stiff are companions of death; the soft and the supple are companions of life.",
    author: 'Lao Tzu',
    work: 'Tao Te Ching',
    source: '76',
    virtues: ['moderation', 'wisdom'],
    themes: ['flexibility', 'life'],
  },

  // ─── CONFUCIUS · Analects (more) ─────────────────────────────────────────
  {
    id: 'confucius-analects-rectify',
    quote: "When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it — this is knowledge.",
    author: 'Confucius',
    work: 'Analects',
    source: '2.17',
    virtues: ['wisdom'],
    themes: ['humility', 'knowledge'],
  },
  {
    id: 'confucius-analects-virtue',
    quote: "Virtue is not left to stand alone. He who practices it will have neighbors.",
    author: 'Confucius',
    work: 'Analects',
    source: '4.25',
    virtues: ['justice'],
    themes: ['virtue', 'community'],
  },
  {
    id: 'confucius-analects-self-cultivation',
    quote: "When you see a worthy person, endeavor to emulate him. When you see an unworthy person, then examine your inner self.",
    author: 'Confucius',
    work: 'Analects',
    source: '4.17',
    virtues: ['wisdom', 'justice'],
    themes: ['self-examination', 'character'],
  },
  {
    id: 'confucius-analects-quiet-mind',
    quote: "The superior man is modest in his speech, but exceeds in his actions.",
    author: 'Confucius',
    work: 'Analects',
    source: '14.27',
    virtues: ['justice', 'moderation'],
    themes: ['integrity', 'action'],
  },
  {
    id: 'confucius-analects-three-paths',
    quote: "By three methods we may learn wisdom: First, by reflection, which is noblest; second, by imitation, which is easiest; and third by experience, which is the bitterest.",
    author: 'Confucius',
    work: 'Analects',
    source: 'attributed',
    virtues: ['wisdom'],
    themes: ['learning', 'reflection'],
  },

  // ─── EMERSON · Self-Reliance ─────────────────────────────────────────────
  {
    id: 'emerson-self-reliance-trust',
    quote: "Trust thyself: every heart vibrates to that iron string.",
    author: 'Ralph Waldo Emerson',
    work: 'Self-Reliance',
    source: '1841',
    virtues: ['courage', 'wisdom'],
    themes: ['self-trust', 'integrity'],
  },
  {
    id: 'emerson-self-reliance-nonconformist',
    quote: "Whoso would be a man must be a nonconformist. He who would gather immortal palms must not be hindered by the name of goodness, but must explore if it be goodness.",
    author: 'Ralph Waldo Emerson',
    work: 'Self-Reliance',
    source: '1841',
    virtues: ['courage'],
    themes: ['independence', 'integrity'],
  },
  {
    id: 'emerson-self-reliance-envy',
    quote: "Envy is ignorance, imitation is suicide. The power which resides in him is new in nature, and none but he knows what that is which he can do, nor does he know until he has tried.",
    author: 'Ralph Waldo Emerson',
    work: 'Self-Reliance',
    source: '1841',
    virtues: ['wisdom', 'courage'],
    themes: ['envy', 'self-knowledge'],
  },
  {
    id: 'emerson-self-reliance-foolish-consistency',
    quote: "A foolish consistency is the hobgoblin of little minds, adored by little statesmen and philosophers and divines.",
    author: 'Ralph Waldo Emerson',
    work: 'Self-Reliance',
    source: '1841',
    virtues: ['wisdom'],
    themes: ['independence', 'truth'],
  },

  // ─── THOREAU · Walden ────────────────────────────────────────────────────
  {
    id: 'thoreau-walden-quiet-desperation',
    quote: "The mass of men lead lives of quiet desperation. What is called resignation is confirmed desperation.",
    author: 'Henry David Thoreau',
    work: 'Walden',
    source: '1854',
    virtues: ['courage', 'wisdom'],
    themes: ['examined life', 'resignation'],
  },
  {
    id: 'thoreau-walden-simplify',
    quote: "Our life is frittered away by detail. Simplify, simplify.",
    author: 'Henry David Thoreau',
    work: 'Walden',
    source: '1854',
    virtues: ['moderation'],
    themes: ['simplicity', 'focus'],
  },
  {
    id: 'thoreau-walden-deliberately',
    quote: "I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.",
    author: 'Henry David Thoreau',
    work: 'Walden',
    source: '1854',
    virtues: ['wisdom', 'courage'],
    themes: ['intention', 'mortality'],
  },
  {
    id: 'thoreau-walden-success',
    quote: "If one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours.",
    author: 'Henry David Thoreau',
    work: 'Walden',
    source: '1854',
    virtues: ['courage'],
    themes: ['action', 'purpose'],
  },

  // ─── BHAGAVAD GITA ───────────────────────────────────────────────────────
  // Stoic-recognizable on duty, equanimity, and action without attachment.
  {
    id: 'gita-2-47-action-fruits',
    quote: "You have a right to perform your prescribed duty, but you are not entitled to the fruits of action. Never consider yourself the cause of the results of your activities, and never be attached to not doing your duty.",
    author: 'Bhagavad Gita',
    work: 'Bhagavad Gita',
    source: '2.47',
    virtues: ['justice', 'moderation'],
    themes: ['duty', 'detachment'],
  },
  {
    id: 'gita-3-35-own-duty',
    quote: "It is better to do one's own duty, however imperfectly, than to assume the duties of another person, however successfully.",
    author: 'Bhagavad Gita',
    work: 'Bhagavad Gita',
    source: '3.35',
    virtues: ['justice', 'wisdom'],
    themes: ['duty', 'authenticity'],
  },
  {
    id: 'gita-6-5-self-conqueror',
    quote: "Lift yourself by your own efforts; do not allow yourself to become depressed. The Self is the friend of the conquered self, but it is the enemy of the unconquered self.",
    author: 'Bhagavad Gita',
    work: 'Bhagavad Gita',
    source: '6.5',
    virtues: ['courage', 'moderation'],
    themes: ['self-mastery', 'discipline'],
  },
  {
    id: 'gita-2-14-impermanence',
    quote: "The contacts of the senses with their objects, which produce the experiences of heat and cold, pleasure and pain, are transitory; they come and go. Endure them bravely.",
    author: 'Bhagavad Gita',
    work: 'Bhagavad Gita',
    source: '2.14',
    virtues: ['courage', 'moderation'],
    themes: ['impermanence', 'endurance'],
  },
  {
    id: 'gita-6-6-mind',
    quote: "For one who has conquered the mind, the mind is the best of friends; but for one who has failed to do so, his very mind will be the greatest enemy.",
    author: 'Bhagavad Gita',
    work: 'Bhagavad Gita',
    source: '6.6',
    virtues: ['moderation', 'wisdom'],
    themes: ['self-mastery', 'mind'],
  },

  // ─── DHAMMAPADA · Buddha ─────────────────────────────────────────────────
  // Selected verses where the Stoic principle of self-mastery, equanimity, or
  // not being captive to passion is unmistakable.
  {
    id: 'dhammapada-1-1-mind',
    quote: "All that we are is the result of what we have thought. The mind is everything. What we think we become.",
    author: 'Buddha',
    work: 'Dhammapada',
    source: '1.1 (commonly translated)',
    virtues: ['wisdom'],
    themes: ['thought', 'character'],
  },
  {
    id: 'dhammapada-50-others',
    quote: "Do not look at the faults of others, or what others have done or not done; observe what you yourself have done and not done.",
    author: 'Buddha',
    work: 'Dhammapada',
    source: '4.50',
    virtues: ['justice', 'wisdom'],
    themes: ['self-examination', 'humility'],
  },
  {
    id: 'dhammapada-103-conquer-self',
    quote: "Though one should conquer a million men in battle, yet he indeed is the noblest victor who has conquered himself.",
    author: 'Buddha',
    work: 'Dhammapada',
    source: '8.103',
    virtues: ['courage', 'moderation'],
    themes: ['self-mastery', 'discipline'],
  },
  {
    id: 'dhammapada-223-anger',
    quote: "Conquer anger by love. Conquer evil by good. Conquer the stingy by giving. Conquer the liar by truth.",
    author: 'Buddha',
    work: 'Dhammapada',
    source: '17.223',
    virtues: ['justice', 'moderation'],
    themes: ['anger', 'virtue'],
  },
  {
    id: 'dhammapada-80-water',
    quote: "As the water-channeler guides the water, as the fletcher fashions the shaft, as the carpenter shapes the wood, so the wise control themselves.",
    author: 'Buddha',
    work: 'Dhammapada',
    source: '6.80',
    virtues: ['moderation', 'wisdom'],
    themes: ['self-mastery', 'discipline'],
  },

  // ─── ETTY HILLESUM · Diaries (1941–1943) ─────────────────────────────────
  // Hillesum's diaries from Nazi-occupied Amsterdam read as live Stoic
  // practice — daily inner work to reclaim equanimity under affliction.
  {
    id: 'hillesum-diaries-1941-06-08-fleas',
    quote: "We have to fight them daily, like fleas, those many small worries about the morrow, for they sap our energies.",
    author: 'Etty Hillesum',
    work: 'An Interrupted Life',
    source: 'Diary, 8 June 1941',
    virtues: ['wisdom', 'moderation'],
    themes: ['attention', 'discipline', 'worry'],
  },
  {
    id: 'hillesum-diaries-1941-moral-duty-peace',
    quote: "Ultimately, we have just one moral duty: to reclaim large areas of peace in ourselves, more and more peace, and to reflect it toward others. And the more peace there is in us, the more peace there will also be in our troubled world.",
    author: 'Etty Hillesum',
    work: 'An Interrupted Life',
    source: 'Diary, 1941',
    virtues: ['justice', 'wisdom', 'moderation'],
    themes: ['inner peace', 'duty', 'service'],
  },

  // ─── SIMONE WEIL · Letters / Gravity and Grace / Need for Roots ────────
  {
    id: 'weil-bousquet-1942-attention-generosity',
    quote: "Attention is the rarest and purest form of generosity.",
    author: 'Simone Weil',
    work: 'Letter to Joë Bousquet',
    source: '13 April 1942',
    virtues: ['justice', 'wisdom'],
    themes: ['attention', 'presence', 'love'],
  },
  {
    id: 'weil-gravity-grace-sins-voids',
    quote: "All sins are attempts to fill voids.",
    author: 'Simone Weil',
    work: 'Gravity and Grace',
    source: '"The Self"',
    virtues: ['wisdom', 'moderation'],
    themes: ['self-knowledge', 'desire', 'discipline'],
  },
  {
    id: 'weil-need-for-roots-rooted',
    quote: "To be rooted is perhaps the most important and least recognized need of the human soul.",
    author: 'Simone Weil',
    work: 'The Need for Roots',
    source: 'Part II, opening',
    virtues: ['justice', 'wisdom'],
    themes: ['belonging', 'community', 'roots'],
  },

  // ─── IRIS MURDOCH · Sovereignty of Good / Existentialists and Mystics ──
  {
    id: 'murdoch-sublime-good-1959-love-realisation',
    quote: "Love is the perception of individuals. Love is the extremely difficult realisation that something other than oneself is real.",
    author: 'Iris Murdoch',
    work: '"The Sublime and the Good"',
    source: 'Existentialists and Mystics, 1959',
    virtues: ['justice', 'wisdom'],
    themes: ['love', 'attention', 'unselfing'],
  },
  {
    id: 'murdoch-sovereignty-personal-fantasy',
    quote: "The chief enemy of excellence in morality (and also in art) is personal fantasy: the tissue of self-aggrandizing and consoling wishes and dreams which prevents one from seeing what is there outside one.",
    author: 'Iris Murdoch',
    work: 'The Sovereignty of Good',
    source: "\"On 'God' and 'Good'\"",
    virtues: ['wisdom', 'courage', 'moderation'],
    themes: ['self-deception', 'attention', 'reality'],
  },
  {
    id: 'murdoch-sovereignty-fat-relentless-ego',
    quote: "In the moral life the enemy is the fat relentless ego.",
    author: 'Iris Murdoch',
    work: 'The Sovereignty of Good',
    source: "\"On 'God' and 'Good'\"",
    virtues: ['moderation', 'wisdom'],
    themes: ['ego', 'self-mastery'],
  },

  // ─── HANNAH ARENDT · On Violence / Eichmann in Jerusalem ───────────────
  {
    id: 'arendt-on-violence-power-opposites',
    quote: "Power and violence are opposites; where the one rules absolutely, the other is absent.",
    author: 'Hannah Arendt',
    work: 'On Violence',
    source: 'Section II',
    virtues: ['justice', 'wisdom'],
    themes: ['power', 'character', 'restraint'],
  },
  {
    id: 'arendt-eichmann-terribly-normal',
    quote: "The trouble with Eichmann was precisely that so many were like him, and that the many were neither perverted nor sadistic, that they were, and still are, terribly and terrifyingly normal.",
    author: 'Hannah Arendt',
    work: 'Eichmann in Jerusalem',
    source: 'Epilogue',
    virtues: ['wisdom', 'justice'],
    themes: ['evil', 'thoughtlessness', 'judgment'],
  },

  // ─── MAYA ANGELOU · Letter to My Daughter ──────────────────────────────
  {
    id: 'angelou-letter-to-daughter-changed-not-reduced',
    quote: "I can be changed by what happens to me. But I refuse to be reduced by it.",
    author: 'Maya Angelou',
    work: 'Letter to My Daughter',
    source: 'Introduction (Random House, 2008)',
    virtues: ['courage', 'wisdom'],
    themes: ['adversity', 'character', 'integrity'],
  },
  {
    id: 'angelou-letter-to-daughter-defeats-not-defeated',
    quote: "You may encounter many defeats, but you must not be defeated.",
    author: 'Maya Angelou',
    work: 'Letter to My Daughter',
    source: 'Introduction (Random House, 2008)',
    virtues: ['courage'],
    themes: ['resilience', 'persistence'],
  },
];

// Helper used by the reading flow: pick candidates filtered by virtue + dedup
// against recent history. Returns up to `limit` quotes.
export function selectCandidates({
  virtueFocus = null,    // 'wisdom' | 'courage' | 'moderation' | 'justice' | null
  excludeIds = [],       // recent quote ids to skip
  limit = 24,
}) {
  const exclude = new Set(excludeIds);
  let pool = STOIC_QUOTES.filter(q => !exclude.has(q.id));
  if (virtueFocus) {
    const matched = pool.filter(q => (q.virtues || []).includes(virtueFocus));
    if (matched.length >= limit) pool = matched;
    else pool = [...matched, ...pool.filter(q => !matched.includes(q))];
  }
  // Light shuffle so candidates aren't in deterministic order across calls.
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, limit);
}
